// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package googlebeta

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/google-beta/v6/google-beta/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type BackupDrBackupPlan struct {
	pulumi.CustomResourceState

	BackupDrBackupPlanId pulumi.StringOutput `pulumi:"backupDrBackupPlanId"`
	// The ID of the backup plan
	BackupPlanId pulumi.StringOutput `pulumi:"backupPlanId"`
	// The backup rules for this 'BackupPlan'. There must be at least one 'BackupRule' message.
	BackupRules BackupDrBackupPlanBackupRuleArrayOutput `pulumi:"backupRules"`
	// Backup vault where the backups gets stored using this Backup plan.
	BackupVault pulumi.StringOutput `pulumi:"backupVault"`
	// The Google Cloud Platform Service Account to be used by the BackupVault for taking backups.
	BackupVaultServiceAccount pulumi.StringOutput `pulumi:"backupVaultServiceAccount"`
	// When the 'BackupPlan' was created.
	CreateTime pulumi.StringOutput `pulumi:"createTime"`
	// The description allows for additional details about 'BackupPlan' and its use cases to be provided.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// The location for the backup plan
	Location pulumi.StringOutput `pulumi:"location"`
	// The name of backup plan resource created
	Name    pulumi.StringOutput `pulumi:"name"`
	Project pulumi.StringOutput `pulumi:"project"`
	// The resource type to which the 'BackupPlan' will be applied. Examples include, "compute.googleapis.com/Instance" and
	// "storage.googleapis.com/Bucket".
	ResourceType pulumi.StringOutput                 `pulumi:"resourceType"`
	Timeouts     BackupDrBackupPlanTimeoutsPtrOutput `pulumi:"timeouts"`
	// When the 'BackupPlan' was last updated.
	UpdateTime pulumi.StringOutput `pulumi:"updateTime"`
}

// NewBackupDrBackupPlan registers a new resource with the given unique name, arguments, and options.
func NewBackupDrBackupPlan(ctx *pulumi.Context,
	name string, args *BackupDrBackupPlanArgs, opts ...pulumi.ResourceOption) (*BackupDrBackupPlan, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.BackupPlanId == nil {
		return nil, errors.New("invalid value for required argument 'BackupPlanId'")
	}
	if args.BackupRules == nil {
		return nil, errors.New("invalid value for required argument 'BackupRules'")
	}
	if args.BackupVault == nil {
		return nil, errors.New("invalid value for required argument 'BackupVault'")
	}
	if args.Location == nil {
		return nil, errors.New("invalid value for required argument 'Location'")
	}
	if args.ResourceType == nil {
		return nil, errors.New("invalid value for required argument 'ResourceType'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource BackupDrBackupPlan
	err = ctx.RegisterPackageResource("google-beta:index/backupDrBackupPlan:BackupDrBackupPlan", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetBackupDrBackupPlan gets an existing BackupDrBackupPlan resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetBackupDrBackupPlan(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *BackupDrBackupPlanState, opts ...pulumi.ResourceOption) (*BackupDrBackupPlan, error) {
	var resource BackupDrBackupPlan
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("google-beta:index/backupDrBackupPlan:BackupDrBackupPlan", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering BackupDrBackupPlan resources.
type backupDrBackupPlanState struct {
	BackupDrBackupPlanId *string `pulumi:"backupDrBackupPlanId"`
	// The ID of the backup plan
	BackupPlanId *string `pulumi:"backupPlanId"`
	// The backup rules for this 'BackupPlan'. There must be at least one 'BackupRule' message.
	BackupRules []BackupDrBackupPlanBackupRule `pulumi:"backupRules"`
	// Backup vault where the backups gets stored using this Backup plan.
	BackupVault *string `pulumi:"backupVault"`
	// The Google Cloud Platform Service Account to be used by the BackupVault for taking backups.
	BackupVaultServiceAccount *string `pulumi:"backupVaultServiceAccount"`
	// When the 'BackupPlan' was created.
	CreateTime *string `pulumi:"createTime"`
	// The description allows for additional details about 'BackupPlan' and its use cases to be provided.
	Description *string `pulumi:"description"`
	// The location for the backup plan
	Location *string `pulumi:"location"`
	// The name of backup plan resource created
	Name    *string `pulumi:"name"`
	Project *string `pulumi:"project"`
	// The resource type to which the 'BackupPlan' will be applied. Examples include, "compute.googleapis.com/Instance" and
	// "storage.googleapis.com/Bucket".
	ResourceType *string                     `pulumi:"resourceType"`
	Timeouts     *BackupDrBackupPlanTimeouts `pulumi:"timeouts"`
	// When the 'BackupPlan' was last updated.
	UpdateTime *string `pulumi:"updateTime"`
}

type BackupDrBackupPlanState struct {
	BackupDrBackupPlanId pulumi.StringPtrInput
	// The ID of the backup plan
	BackupPlanId pulumi.StringPtrInput
	// The backup rules for this 'BackupPlan'. There must be at least one 'BackupRule' message.
	BackupRules BackupDrBackupPlanBackupRuleArrayInput
	// Backup vault where the backups gets stored using this Backup plan.
	BackupVault pulumi.StringPtrInput
	// The Google Cloud Platform Service Account to be used by the BackupVault for taking backups.
	BackupVaultServiceAccount pulumi.StringPtrInput
	// When the 'BackupPlan' was created.
	CreateTime pulumi.StringPtrInput
	// The description allows for additional details about 'BackupPlan' and its use cases to be provided.
	Description pulumi.StringPtrInput
	// The location for the backup plan
	Location pulumi.StringPtrInput
	// The name of backup plan resource created
	Name    pulumi.StringPtrInput
	Project pulumi.StringPtrInput
	// The resource type to which the 'BackupPlan' will be applied. Examples include, "compute.googleapis.com/Instance" and
	// "storage.googleapis.com/Bucket".
	ResourceType pulumi.StringPtrInput
	Timeouts     BackupDrBackupPlanTimeoutsPtrInput
	// When the 'BackupPlan' was last updated.
	UpdateTime pulumi.StringPtrInput
}

func (BackupDrBackupPlanState) ElementType() reflect.Type {
	return reflect.TypeOf((*backupDrBackupPlanState)(nil)).Elem()
}

type backupDrBackupPlanArgs struct {
	BackupDrBackupPlanId *string `pulumi:"backupDrBackupPlanId"`
	// The ID of the backup plan
	BackupPlanId string `pulumi:"backupPlanId"`
	// The backup rules for this 'BackupPlan'. There must be at least one 'BackupRule' message.
	BackupRules []BackupDrBackupPlanBackupRule `pulumi:"backupRules"`
	// Backup vault where the backups gets stored using this Backup plan.
	BackupVault string `pulumi:"backupVault"`
	// The description allows for additional details about 'BackupPlan' and its use cases to be provided.
	Description *string `pulumi:"description"`
	// The location for the backup plan
	Location string  `pulumi:"location"`
	Project  *string `pulumi:"project"`
	// The resource type to which the 'BackupPlan' will be applied. Examples include, "compute.googleapis.com/Instance" and
	// "storage.googleapis.com/Bucket".
	ResourceType string                      `pulumi:"resourceType"`
	Timeouts     *BackupDrBackupPlanTimeouts `pulumi:"timeouts"`
}

// The set of arguments for constructing a BackupDrBackupPlan resource.
type BackupDrBackupPlanArgs struct {
	BackupDrBackupPlanId pulumi.StringPtrInput
	// The ID of the backup plan
	BackupPlanId pulumi.StringInput
	// The backup rules for this 'BackupPlan'. There must be at least one 'BackupRule' message.
	BackupRules BackupDrBackupPlanBackupRuleArrayInput
	// Backup vault where the backups gets stored using this Backup plan.
	BackupVault pulumi.StringInput
	// The description allows for additional details about 'BackupPlan' and its use cases to be provided.
	Description pulumi.StringPtrInput
	// The location for the backup plan
	Location pulumi.StringInput
	Project  pulumi.StringPtrInput
	// The resource type to which the 'BackupPlan' will be applied. Examples include, "compute.googleapis.com/Instance" and
	// "storage.googleapis.com/Bucket".
	ResourceType pulumi.StringInput
	Timeouts     BackupDrBackupPlanTimeoutsPtrInput
}

func (BackupDrBackupPlanArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*backupDrBackupPlanArgs)(nil)).Elem()
}

type BackupDrBackupPlanInput interface {
	pulumi.Input

	ToBackupDrBackupPlanOutput() BackupDrBackupPlanOutput
	ToBackupDrBackupPlanOutputWithContext(ctx context.Context) BackupDrBackupPlanOutput
}

func (*BackupDrBackupPlan) ElementType() reflect.Type {
	return reflect.TypeOf((**BackupDrBackupPlan)(nil)).Elem()
}

func (i *BackupDrBackupPlan) ToBackupDrBackupPlanOutput() BackupDrBackupPlanOutput {
	return i.ToBackupDrBackupPlanOutputWithContext(context.Background())
}

func (i *BackupDrBackupPlan) ToBackupDrBackupPlanOutputWithContext(ctx context.Context) BackupDrBackupPlanOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BackupDrBackupPlanOutput)
}

type BackupDrBackupPlanOutput struct{ *pulumi.OutputState }

func (BackupDrBackupPlanOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**BackupDrBackupPlan)(nil)).Elem()
}

func (o BackupDrBackupPlanOutput) ToBackupDrBackupPlanOutput() BackupDrBackupPlanOutput {
	return o
}

func (o BackupDrBackupPlanOutput) ToBackupDrBackupPlanOutputWithContext(ctx context.Context) BackupDrBackupPlanOutput {
	return o
}

func (o BackupDrBackupPlanOutput) BackupDrBackupPlanId() pulumi.StringOutput {
	return o.ApplyT(func(v *BackupDrBackupPlan) pulumi.StringOutput { return v.BackupDrBackupPlanId }).(pulumi.StringOutput)
}

// The ID of the backup plan
func (o BackupDrBackupPlanOutput) BackupPlanId() pulumi.StringOutput {
	return o.ApplyT(func(v *BackupDrBackupPlan) pulumi.StringOutput { return v.BackupPlanId }).(pulumi.StringOutput)
}

// The backup rules for this 'BackupPlan'. There must be at least one 'BackupRule' message.
func (o BackupDrBackupPlanOutput) BackupRules() BackupDrBackupPlanBackupRuleArrayOutput {
	return o.ApplyT(func(v *BackupDrBackupPlan) BackupDrBackupPlanBackupRuleArrayOutput { return v.BackupRules }).(BackupDrBackupPlanBackupRuleArrayOutput)
}

// Backup vault where the backups gets stored using this Backup plan.
func (o BackupDrBackupPlanOutput) BackupVault() pulumi.StringOutput {
	return o.ApplyT(func(v *BackupDrBackupPlan) pulumi.StringOutput { return v.BackupVault }).(pulumi.StringOutput)
}

// The Google Cloud Platform Service Account to be used by the BackupVault for taking backups.
func (o BackupDrBackupPlanOutput) BackupVaultServiceAccount() pulumi.StringOutput {
	return o.ApplyT(func(v *BackupDrBackupPlan) pulumi.StringOutput { return v.BackupVaultServiceAccount }).(pulumi.StringOutput)
}

// When the 'BackupPlan' was created.
func (o BackupDrBackupPlanOutput) CreateTime() pulumi.StringOutput {
	return o.ApplyT(func(v *BackupDrBackupPlan) pulumi.StringOutput { return v.CreateTime }).(pulumi.StringOutput)
}

// The description allows for additional details about 'BackupPlan' and its use cases to be provided.
func (o BackupDrBackupPlanOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *BackupDrBackupPlan) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// The location for the backup plan
func (o BackupDrBackupPlanOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v *BackupDrBackupPlan) pulumi.StringOutput { return v.Location }).(pulumi.StringOutput)
}

// The name of backup plan resource created
func (o BackupDrBackupPlanOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *BackupDrBackupPlan) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o BackupDrBackupPlanOutput) Project() pulumi.StringOutput {
	return o.ApplyT(func(v *BackupDrBackupPlan) pulumi.StringOutput { return v.Project }).(pulumi.StringOutput)
}

// The resource type to which the 'BackupPlan' will be applied. Examples include, "compute.googleapis.com/Instance" and
// "storage.googleapis.com/Bucket".
func (o BackupDrBackupPlanOutput) ResourceType() pulumi.StringOutput {
	return o.ApplyT(func(v *BackupDrBackupPlan) pulumi.StringOutput { return v.ResourceType }).(pulumi.StringOutput)
}

func (o BackupDrBackupPlanOutput) Timeouts() BackupDrBackupPlanTimeoutsPtrOutput {
	return o.ApplyT(func(v *BackupDrBackupPlan) BackupDrBackupPlanTimeoutsPtrOutput { return v.Timeouts }).(BackupDrBackupPlanTimeoutsPtrOutput)
}

// When the 'BackupPlan' was last updated.
func (o BackupDrBackupPlanOutput) UpdateTime() pulumi.StringOutput {
	return o.ApplyT(func(v *BackupDrBackupPlan) pulumi.StringOutput { return v.UpdateTime }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*BackupDrBackupPlanInput)(nil)).Elem(), &BackupDrBackupPlan{})
	pulumi.RegisterOutputType(BackupDrBackupPlanOutput{})
}
