// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package googlebeta

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/google-beta/v6/google-beta/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type CloudRunV2JobIamPolicy struct {
	pulumi.CustomResourceState

	CloudRunV2JobIamPolicyId pulumi.StringOutput `pulumi:"cloudRunV2JobIamPolicyId"`
	Etag                     pulumi.StringOutput `pulumi:"etag"`
	Location                 pulumi.StringOutput `pulumi:"location"`
	Name                     pulumi.StringOutput `pulumi:"name"`
	PolicyData               pulumi.StringOutput `pulumi:"policyData"`
	Project                  pulumi.StringOutput `pulumi:"project"`
}

// NewCloudRunV2JobIamPolicy registers a new resource with the given unique name, arguments, and options.
func NewCloudRunV2JobIamPolicy(ctx *pulumi.Context,
	name string, args *CloudRunV2JobIamPolicyArgs, opts ...pulumi.ResourceOption) (*CloudRunV2JobIamPolicy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.PolicyData == nil {
		return nil, errors.New("invalid value for required argument 'PolicyData'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource CloudRunV2JobIamPolicy
	err = ctx.RegisterPackageResource("google-beta:index/cloudRunV2JobIamPolicy:CloudRunV2JobIamPolicy", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCloudRunV2JobIamPolicy gets an existing CloudRunV2JobIamPolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCloudRunV2JobIamPolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CloudRunV2JobIamPolicyState, opts ...pulumi.ResourceOption) (*CloudRunV2JobIamPolicy, error) {
	var resource CloudRunV2JobIamPolicy
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("google-beta:index/cloudRunV2JobIamPolicy:CloudRunV2JobIamPolicy", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CloudRunV2JobIamPolicy resources.
type cloudRunV2JobIamPolicyState struct {
	CloudRunV2JobIamPolicyId *string `pulumi:"cloudRunV2JobIamPolicyId"`
	Etag                     *string `pulumi:"etag"`
	Location                 *string `pulumi:"location"`
	Name                     *string `pulumi:"name"`
	PolicyData               *string `pulumi:"policyData"`
	Project                  *string `pulumi:"project"`
}

type CloudRunV2JobIamPolicyState struct {
	CloudRunV2JobIamPolicyId pulumi.StringPtrInput
	Etag                     pulumi.StringPtrInput
	Location                 pulumi.StringPtrInput
	Name                     pulumi.StringPtrInput
	PolicyData               pulumi.StringPtrInput
	Project                  pulumi.StringPtrInput
}

func (CloudRunV2JobIamPolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*cloudRunV2JobIamPolicyState)(nil)).Elem()
}

type cloudRunV2JobIamPolicyArgs struct {
	CloudRunV2JobIamPolicyId *string `pulumi:"cloudRunV2JobIamPolicyId"`
	Location                 *string `pulumi:"location"`
	Name                     *string `pulumi:"name"`
	PolicyData               string  `pulumi:"policyData"`
	Project                  *string `pulumi:"project"`
}

// The set of arguments for constructing a CloudRunV2JobIamPolicy resource.
type CloudRunV2JobIamPolicyArgs struct {
	CloudRunV2JobIamPolicyId pulumi.StringPtrInput
	Location                 pulumi.StringPtrInput
	Name                     pulumi.StringPtrInput
	PolicyData               pulumi.StringInput
	Project                  pulumi.StringPtrInput
}

func (CloudRunV2JobIamPolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*cloudRunV2JobIamPolicyArgs)(nil)).Elem()
}

type CloudRunV2JobIamPolicyInput interface {
	pulumi.Input

	ToCloudRunV2JobIamPolicyOutput() CloudRunV2JobIamPolicyOutput
	ToCloudRunV2JobIamPolicyOutputWithContext(ctx context.Context) CloudRunV2JobIamPolicyOutput
}

func (*CloudRunV2JobIamPolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**CloudRunV2JobIamPolicy)(nil)).Elem()
}

func (i *CloudRunV2JobIamPolicy) ToCloudRunV2JobIamPolicyOutput() CloudRunV2JobIamPolicyOutput {
	return i.ToCloudRunV2JobIamPolicyOutputWithContext(context.Background())
}

func (i *CloudRunV2JobIamPolicy) ToCloudRunV2JobIamPolicyOutputWithContext(ctx context.Context) CloudRunV2JobIamPolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudRunV2JobIamPolicyOutput)
}

type CloudRunV2JobIamPolicyOutput struct{ *pulumi.OutputState }

func (CloudRunV2JobIamPolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CloudRunV2JobIamPolicy)(nil)).Elem()
}

func (o CloudRunV2JobIamPolicyOutput) ToCloudRunV2JobIamPolicyOutput() CloudRunV2JobIamPolicyOutput {
	return o
}

func (o CloudRunV2JobIamPolicyOutput) ToCloudRunV2JobIamPolicyOutputWithContext(ctx context.Context) CloudRunV2JobIamPolicyOutput {
	return o
}

func (o CloudRunV2JobIamPolicyOutput) CloudRunV2JobIamPolicyId() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudRunV2JobIamPolicy) pulumi.StringOutput { return v.CloudRunV2JobIamPolicyId }).(pulumi.StringOutput)
}

func (o CloudRunV2JobIamPolicyOutput) Etag() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudRunV2JobIamPolicy) pulumi.StringOutput { return v.Etag }).(pulumi.StringOutput)
}

func (o CloudRunV2JobIamPolicyOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudRunV2JobIamPolicy) pulumi.StringOutput { return v.Location }).(pulumi.StringOutput)
}

func (o CloudRunV2JobIamPolicyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudRunV2JobIamPolicy) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o CloudRunV2JobIamPolicyOutput) PolicyData() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudRunV2JobIamPolicy) pulumi.StringOutput { return v.PolicyData }).(pulumi.StringOutput)
}

func (o CloudRunV2JobIamPolicyOutput) Project() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudRunV2JobIamPolicy) pulumi.StringOutput { return v.Project }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CloudRunV2JobIamPolicyInput)(nil)).Elem(), &CloudRunV2JobIamPolicy{})
	pulumi.RegisterOutputType(CloudRunV2JobIamPolicyOutput{})
}
