// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package googlebeta

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/google-beta/v6/google-beta/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ContainerAwsCluster struct {
	pulumi.CustomResourceState

	// Optional. Annotations on the cluster. This field has the same restrictions as Kubernetes annotations. The total size of
	// all keys and values combined is limited to 256k. Key can have 2 segments: prefix (optional) and name (required),
	// separated by a slash (/). Prefix must be a DNS subdomain. Name must be 63 characters or less, begin and end with
	// alphanumerics, with dashes (-), underscores (_), dots (.), and alphanumerics between. **Note**: This field is
	// non-authoritative, and will only manage the annotations present in your configuration. Please refer to the field
	// `effective_annotations` for all of the annotations present on the resource.
	Annotations pulumi.StringMapOutput `pulumi:"annotations"`
	// Configuration related to the cluster RBAC settings.
	Authorization ContainerAwsClusterAuthorizationOutput `pulumi:"authorization"`
	// The AWS region where the cluster runs. Each Google Cloud region supports a subset of nearby AWS regions. You can call to
	// list all supported AWS regions within a given Google Cloud region.
	AwsRegion pulumi.StringOutput `pulumi:"awsRegion"`
	// Configuration options for the Binary Authorization feature.
	BinaryAuthorization   ContainerAwsClusterBinaryAuthorizationPtrOutput `pulumi:"binaryAuthorization"`
	ContainerAwsClusterId pulumi.StringOutput                             `pulumi:"containerAwsClusterId"`
	// Configuration related to the cluster control plane.
	ControlPlane ContainerAwsClusterControlPlaneOutput `pulumi:"controlPlane"`
	// Output only. The time at which this cluster was created.
	CreateTime pulumi.StringOutput `pulumi:"createTime"`
	// Optional. A human readable description of this cluster. Cannot be longer than 255 UTF-8 encoded bytes.
	Description          pulumi.StringPtrOutput `pulumi:"description"`
	EffectiveAnnotations pulumi.StringMapOutput `pulumi:"effectiveAnnotations"`
	// Output only. The endpoint of the cluster's API server.
	Endpoint pulumi.StringOutput `pulumi:"endpoint"`
	// Allows clients to perform consistent read-modify-writes through optimistic concurrency control. May be sent on update
	// and delete requests to ensure the client has an up-to-date value before proceeding.
	Etag pulumi.StringOutput `pulumi:"etag"`
	// Fleet configuration.
	Fleet ContainerAwsClusterFleetOutput `pulumi:"fleet"`
	// The location for the resource
	Location pulumi.StringOutput `pulumi:"location"`
	// Logging configuration.
	LoggingConfig ContainerAwsClusterLoggingConfigPtrOutput `pulumi:"loggingConfig"`
	// The name of this resource.
	Name pulumi.StringOutput `pulumi:"name"`
	// Cluster-wide networking configuration.
	Networking ContainerAwsClusterNetworkingOutput `pulumi:"networking"`
	// The project for the resource
	Project pulumi.StringOutput `pulumi:"project"`
	// Output only. If set, there are currently changes in flight to the cluster.
	Reconciling pulumi.BoolOutput `pulumi:"reconciling"`
	// Output only. The current state of the cluster. Possible values: STATE_UNSPECIFIED, PROVISIONING, RUNNING, RECONCILING,
	// STOPPING, ERROR, DEGRADED
	State    pulumi.StringOutput                  `pulumi:"state"`
	Timeouts ContainerAwsClusterTimeoutsPtrOutput `pulumi:"timeouts"`
	// Output only. A globally unique identifier for the cluster.
	Uid pulumi.StringOutput `pulumi:"uid"`
	// Output only. The time at which this cluster was last updated.
	UpdateTime pulumi.StringOutput `pulumi:"updateTime"`
	// Output only. Workload Identity settings.
	WorkloadIdentityConfigs ContainerAwsClusterWorkloadIdentityConfigArrayOutput `pulumi:"workloadIdentityConfigs"`
}

// NewContainerAwsCluster registers a new resource with the given unique name, arguments, and options.
func NewContainerAwsCluster(ctx *pulumi.Context,
	name string, args *ContainerAwsClusterArgs, opts ...pulumi.ResourceOption) (*ContainerAwsCluster, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Authorization == nil {
		return nil, errors.New("invalid value for required argument 'Authorization'")
	}
	if args.AwsRegion == nil {
		return nil, errors.New("invalid value for required argument 'AwsRegion'")
	}
	if args.ControlPlane == nil {
		return nil, errors.New("invalid value for required argument 'ControlPlane'")
	}
	if args.Fleet == nil {
		return nil, errors.New("invalid value for required argument 'Fleet'")
	}
	if args.Location == nil {
		return nil, errors.New("invalid value for required argument 'Location'")
	}
	if args.Networking == nil {
		return nil, errors.New("invalid value for required argument 'Networking'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource ContainerAwsCluster
	err = ctx.RegisterPackageResource("google-beta:index/containerAwsCluster:ContainerAwsCluster", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetContainerAwsCluster gets an existing ContainerAwsCluster resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetContainerAwsCluster(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ContainerAwsClusterState, opts ...pulumi.ResourceOption) (*ContainerAwsCluster, error) {
	var resource ContainerAwsCluster
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("google-beta:index/containerAwsCluster:ContainerAwsCluster", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ContainerAwsCluster resources.
type containerAwsClusterState struct {
	// Optional. Annotations on the cluster. This field has the same restrictions as Kubernetes annotations. The total size of
	// all keys and values combined is limited to 256k. Key can have 2 segments: prefix (optional) and name (required),
	// separated by a slash (/). Prefix must be a DNS subdomain. Name must be 63 characters or less, begin and end with
	// alphanumerics, with dashes (-), underscores (_), dots (.), and alphanumerics between. **Note**: This field is
	// non-authoritative, and will only manage the annotations present in your configuration. Please refer to the field
	// `effective_annotations` for all of the annotations present on the resource.
	Annotations map[string]string `pulumi:"annotations"`
	// Configuration related to the cluster RBAC settings.
	Authorization *ContainerAwsClusterAuthorization `pulumi:"authorization"`
	// The AWS region where the cluster runs. Each Google Cloud region supports a subset of nearby AWS regions. You can call to
	// list all supported AWS regions within a given Google Cloud region.
	AwsRegion *string `pulumi:"awsRegion"`
	// Configuration options for the Binary Authorization feature.
	BinaryAuthorization   *ContainerAwsClusterBinaryAuthorization `pulumi:"binaryAuthorization"`
	ContainerAwsClusterId *string                                 `pulumi:"containerAwsClusterId"`
	// Configuration related to the cluster control plane.
	ControlPlane *ContainerAwsClusterControlPlane `pulumi:"controlPlane"`
	// Output only. The time at which this cluster was created.
	CreateTime *string `pulumi:"createTime"`
	// Optional. A human readable description of this cluster. Cannot be longer than 255 UTF-8 encoded bytes.
	Description          *string           `pulumi:"description"`
	EffectiveAnnotations map[string]string `pulumi:"effectiveAnnotations"`
	// Output only. The endpoint of the cluster's API server.
	Endpoint *string `pulumi:"endpoint"`
	// Allows clients to perform consistent read-modify-writes through optimistic concurrency control. May be sent on update
	// and delete requests to ensure the client has an up-to-date value before proceeding.
	Etag *string `pulumi:"etag"`
	// Fleet configuration.
	Fleet *ContainerAwsClusterFleet `pulumi:"fleet"`
	// The location for the resource
	Location *string `pulumi:"location"`
	// Logging configuration.
	LoggingConfig *ContainerAwsClusterLoggingConfig `pulumi:"loggingConfig"`
	// The name of this resource.
	Name *string `pulumi:"name"`
	// Cluster-wide networking configuration.
	Networking *ContainerAwsClusterNetworking `pulumi:"networking"`
	// The project for the resource
	Project *string `pulumi:"project"`
	// Output only. If set, there are currently changes in flight to the cluster.
	Reconciling *bool `pulumi:"reconciling"`
	// Output only. The current state of the cluster. Possible values: STATE_UNSPECIFIED, PROVISIONING, RUNNING, RECONCILING,
	// STOPPING, ERROR, DEGRADED
	State    *string                      `pulumi:"state"`
	Timeouts *ContainerAwsClusterTimeouts `pulumi:"timeouts"`
	// Output only. A globally unique identifier for the cluster.
	Uid *string `pulumi:"uid"`
	// Output only. The time at which this cluster was last updated.
	UpdateTime *string `pulumi:"updateTime"`
	// Output only. Workload Identity settings.
	WorkloadIdentityConfigs []ContainerAwsClusterWorkloadIdentityConfig `pulumi:"workloadIdentityConfigs"`
}

type ContainerAwsClusterState struct {
	// Optional. Annotations on the cluster. This field has the same restrictions as Kubernetes annotations. The total size of
	// all keys and values combined is limited to 256k. Key can have 2 segments: prefix (optional) and name (required),
	// separated by a slash (/). Prefix must be a DNS subdomain. Name must be 63 characters or less, begin and end with
	// alphanumerics, with dashes (-), underscores (_), dots (.), and alphanumerics between. **Note**: This field is
	// non-authoritative, and will only manage the annotations present in your configuration. Please refer to the field
	// `effective_annotations` for all of the annotations present on the resource.
	Annotations pulumi.StringMapInput
	// Configuration related to the cluster RBAC settings.
	Authorization ContainerAwsClusterAuthorizationPtrInput
	// The AWS region where the cluster runs. Each Google Cloud region supports a subset of nearby AWS regions. You can call to
	// list all supported AWS regions within a given Google Cloud region.
	AwsRegion pulumi.StringPtrInput
	// Configuration options for the Binary Authorization feature.
	BinaryAuthorization   ContainerAwsClusterBinaryAuthorizationPtrInput
	ContainerAwsClusterId pulumi.StringPtrInput
	// Configuration related to the cluster control plane.
	ControlPlane ContainerAwsClusterControlPlanePtrInput
	// Output only. The time at which this cluster was created.
	CreateTime pulumi.StringPtrInput
	// Optional. A human readable description of this cluster. Cannot be longer than 255 UTF-8 encoded bytes.
	Description          pulumi.StringPtrInput
	EffectiveAnnotations pulumi.StringMapInput
	// Output only. The endpoint of the cluster's API server.
	Endpoint pulumi.StringPtrInput
	// Allows clients to perform consistent read-modify-writes through optimistic concurrency control. May be sent on update
	// and delete requests to ensure the client has an up-to-date value before proceeding.
	Etag pulumi.StringPtrInput
	// Fleet configuration.
	Fleet ContainerAwsClusterFleetPtrInput
	// The location for the resource
	Location pulumi.StringPtrInput
	// Logging configuration.
	LoggingConfig ContainerAwsClusterLoggingConfigPtrInput
	// The name of this resource.
	Name pulumi.StringPtrInput
	// Cluster-wide networking configuration.
	Networking ContainerAwsClusterNetworkingPtrInput
	// The project for the resource
	Project pulumi.StringPtrInput
	// Output only. If set, there are currently changes in flight to the cluster.
	Reconciling pulumi.BoolPtrInput
	// Output only. The current state of the cluster. Possible values: STATE_UNSPECIFIED, PROVISIONING, RUNNING, RECONCILING,
	// STOPPING, ERROR, DEGRADED
	State    pulumi.StringPtrInput
	Timeouts ContainerAwsClusterTimeoutsPtrInput
	// Output only. A globally unique identifier for the cluster.
	Uid pulumi.StringPtrInput
	// Output only. The time at which this cluster was last updated.
	UpdateTime pulumi.StringPtrInput
	// Output only. Workload Identity settings.
	WorkloadIdentityConfigs ContainerAwsClusterWorkloadIdentityConfigArrayInput
}

func (ContainerAwsClusterState) ElementType() reflect.Type {
	return reflect.TypeOf((*containerAwsClusterState)(nil)).Elem()
}

type containerAwsClusterArgs struct {
	// Optional. Annotations on the cluster. This field has the same restrictions as Kubernetes annotations. The total size of
	// all keys and values combined is limited to 256k. Key can have 2 segments: prefix (optional) and name (required),
	// separated by a slash (/). Prefix must be a DNS subdomain. Name must be 63 characters or less, begin and end with
	// alphanumerics, with dashes (-), underscores (_), dots (.), and alphanumerics between. **Note**: This field is
	// non-authoritative, and will only manage the annotations present in your configuration. Please refer to the field
	// `effective_annotations` for all of the annotations present on the resource.
	Annotations map[string]string `pulumi:"annotations"`
	// Configuration related to the cluster RBAC settings.
	Authorization ContainerAwsClusterAuthorization `pulumi:"authorization"`
	// The AWS region where the cluster runs. Each Google Cloud region supports a subset of nearby AWS regions. You can call to
	// list all supported AWS regions within a given Google Cloud region.
	AwsRegion string `pulumi:"awsRegion"`
	// Configuration options for the Binary Authorization feature.
	BinaryAuthorization   *ContainerAwsClusterBinaryAuthorization `pulumi:"binaryAuthorization"`
	ContainerAwsClusterId *string                                 `pulumi:"containerAwsClusterId"`
	// Configuration related to the cluster control plane.
	ControlPlane ContainerAwsClusterControlPlane `pulumi:"controlPlane"`
	// Optional. A human readable description of this cluster. Cannot be longer than 255 UTF-8 encoded bytes.
	Description *string `pulumi:"description"`
	// Fleet configuration.
	Fleet ContainerAwsClusterFleet `pulumi:"fleet"`
	// The location for the resource
	Location string `pulumi:"location"`
	// Logging configuration.
	LoggingConfig *ContainerAwsClusterLoggingConfig `pulumi:"loggingConfig"`
	// The name of this resource.
	Name *string `pulumi:"name"`
	// Cluster-wide networking configuration.
	Networking ContainerAwsClusterNetworking `pulumi:"networking"`
	// The project for the resource
	Project  *string                      `pulumi:"project"`
	Timeouts *ContainerAwsClusterTimeouts `pulumi:"timeouts"`
}

// The set of arguments for constructing a ContainerAwsCluster resource.
type ContainerAwsClusterArgs struct {
	// Optional. Annotations on the cluster. This field has the same restrictions as Kubernetes annotations. The total size of
	// all keys and values combined is limited to 256k. Key can have 2 segments: prefix (optional) and name (required),
	// separated by a slash (/). Prefix must be a DNS subdomain. Name must be 63 characters or less, begin and end with
	// alphanumerics, with dashes (-), underscores (_), dots (.), and alphanumerics between. **Note**: This field is
	// non-authoritative, and will only manage the annotations present in your configuration. Please refer to the field
	// `effective_annotations` for all of the annotations present on the resource.
	Annotations pulumi.StringMapInput
	// Configuration related to the cluster RBAC settings.
	Authorization ContainerAwsClusterAuthorizationInput
	// The AWS region where the cluster runs. Each Google Cloud region supports a subset of nearby AWS regions. You can call to
	// list all supported AWS regions within a given Google Cloud region.
	AwsRegion pulumi.StringInput
	// Configuration options for the Binary Authorization feature.
	BinaryAuthorization   ContainerAwsClusterBinaryAuthorizationPtrInput
	ContainerAwsClusterId pulumi.StringPtrInput
	// Configuration related to the cluster control plane.
	ControlPlane ContainerAwsClusterControlPlaneInput
	// Optional. A human readable description of this cluster. Cannot be longer than 255 UTF-8 encoded bytes.
	Description pulumi.StringPtrInput
	// Fleet configuration.
	Fleet ContainerAwsClusterFleetInput
	// The location for the resource
	Location pulumi.StringInput
	// Logging configuration.
	LoggingConfig ContainerAwsClusterLoggingConfigPtrInput
	// The name of this resource.
	Name pulumi.StringPtrInput
	// Cluster-wide networking configuration.
	Networking ContainerAwsClusterNetworkingInput
	// The project for the resource
	Project  pulumi.StringPtrInput
	Timeouts ContainerAwsClusterTimeoutsPtrInput
}

func (ContainerAwsClusterArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*containerAwsClusterArgs)(nil)).Elem()
}

type ContainerAwsClusterInput interface {
	pulumi.Input

	ToContainerAwsClusterOutput() ContainerAwsClusterOutput
	ToContainerAwsClusterOutputWithContext(ctx context.Context) ContainerAwsClusterOutput
}

func (*ContainerAwsCluster) ElementType() reflect.Type {
	return reflect.TypeOf((**ContainerAwsCluster)(nil)).Elem()
}

func (i *ContainerAwsCluster) ToContainerAwsClusterOutput() ContainerAwsClusterOutput {
	return i.ToContainerAwsClusterOutputWithContext(context.Background())
}

func (i *ContainerAwsCluster) ToContainerAwsClusterOutputWithContext(ctx context.Context) ContainerAwsClusterOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ContainerAwsClusterOutput)
}

type ContainerAwsClusterOutput struct{ *pulumi.OutputState }

func (ContainerAwsClusterOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ContainerAwsCluster)(nil)).Elem()
}

func (o ContainerAwsClusterOutput) ToContainerAwsClusterOutput() ContainerAwsClusterOutput {
	return o
}

func (o ContainerAwsClusterOutput) ToContainerAwsClusterOutputWithContext(ctx context.Context) ContainerAwsClusterOutput {
	return o
}

// Optional. Annotations on the cluster. This field has the same restrictions as Kubernetes annotations. The total size of
// all keys and values combined is limited to 256k. Key can have 2 segments: prefix (optional) and name (required),
// separated by a slash (/). Prefix must be a DNS subdomain. Name must be 63 characters or less, begin and end with
// alphanumerics, with dashes (-), underscores (_), dots (.), and alphanumerics between. **Note**: This field is
// non-authoritative, and will only manage the annotations present in your configuration. Please refer to the field
// `effective_annotations` for all of the annotations present on the resource.
func (o ContainerAwsClusterOutput) Annotations() pulumi.StringMapOutput {
	return o.ApplyT(func(v *ContainerAwsCluster) pulumi.StringMapOutput { return v.Annotations }).(pulumi.StringMapOutput)
}

// Configuration related to the cluster RBAC settings.
func (o ContainerAwsClusterOutput) Authorization() ContainerAwsClusterAuthorizationOutput {
	return o.ApplyT(func(v *ContainerAwsCluster) ContainerAwsClusterAuthorizationOutput { return v.Authorization }).(ContainerAwsClusterAuthorizationOutput)
}

// The AWS region where the cluster runs. Each Google Cloud region supports a subset of nearby AWS regions. You can call to
// list all supported AWS regions within a given Google Cloud region.
func (o ContainerAwsClusterOutput) AwsRegion() pulumi.StringOutput {
	return o.ApplyT(func(v *ContainerAwsCluster) pulumi.StringOutput { return v.AwsRegion }).(pulumi.StringOutput)
}

// Configuration options for the Binary Authorization feature.
func (o ContainerAwsClusterOutput) BinaryAuthorization() ContainerAwsClusterBinaryAuthorizationPtrOutput {
	return o.ApplyT(func(v *ContainerAwsCluster) ContainerAwsClusterBinaryAuthorizationPtrOutput {
		return v.BinaryAuthorization
	}).(ContainerAwsClusterBinaryAuthorizationPtrOutput)
}

func (o ContainerAwsClusterOutput) ContainerAwsClusterId() pulumi.StringOutput {
	return o.ApplyT(func(v *ContainerAwsCluster) pulumi.StringOutput { return v.ContainerAwsClusterId }).(pulumi.StringOutput)
}

// Configuration related to the cluster control plane.
func (o ContainerAwsClusterOutput) ControlPlane() ContainerAwsClusterControlPlaneOutput {
	return o.ApplyT(func(v *ContainerAwsCluster) ContainerAwsClusterControlPlaneOutput { return v.ControlPlane }).(ContainerAwsClusterControlPlaneOutput)
}

// Output only. The time at which this cluster was created.
func (o ContainerAwsClusterOutput) CreateTime() pulumi.StringOutput {
	return o.ApplyT(func(v *ContainerAwsCluster) pulumi.StringOutput { return v.CreateTime }).(pulumi.StringOutput)
}

// Optional. A human readable description of this cluster. Cannot be longer than 255 UTF-8 encoded bytes.
func (o ContainerAwsClusterOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ContainerAwsCluster) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

func (o ContainerAwsClusterOutput) EffectiveAnnotations() pulumi.StringMapOutput {
	return o.ApplyT(func(v *ContainerAwsCluster) pulumi.StringMapOutput { return v.EffectiveAnnotations }).(pulumi.StringMapOutput)
}

// Output only. The endpoint of the cluster's API server.
func (o ContainerAwsClusterOutput) Endpoint() pulumi.StringOutput {
	return o.ApplyT(func(v *ContainerAwsCluster) pulumi.StringOutput { return v.Endpoint }).(pulumi.StringOutput)
}

// Allows clients to perform consistent read-modify-writes through optimistic concurrency control. May be sent on update
// and delete requests to ensure the client has an up-to-date value before proceeding.
func (o ContainerAwsClusterOutput) Etag() pulumi.StringOutput {
	return o.ApplyT(func(v *ContainerAwsCluster) pulumi.StringOutput { return v.Etag }).(pulumi.StringOutput)
}

// Fleet configuration.
func (o ContainerAwsClusterOutput) Fleet() ContainerAwsClusterFleetOutput {
	return o.ApplyT(func(v *ContainerAwsCluster) ContainerAwsClusterFleetOutput { return v.Fleet }).(ContainerAwsClusterFleetOutput)
}

// The location for the resource
func (o ContainerAwsClusterOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v *ContainerAwsCluster) pulumi.StringOutput { return v.Location }).(pulumi.StringOutput)
}

// Logging configuration.
func (o ContainerAwsClusterOutput) LoggingConfig() ContainerAwsClusterLoggingConfigPtrOutput {
	return o.ApplyT(func(v *ContainerAwsCluster) ContainerAwsClusterLoggingConfigPtrOutput { return v.LoggingConfig }).(ContainerAwsClusterLoggingConfigPtrOutput)
}

// The name of this resource.
func (o ContainerAwsClusterOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ContainerAwsCluster) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Cluster-wide networking configuration.
func (o ContainerAwsClusterOutput) Networking() ContainerAwsClusterNetworkingOutput {
	return o.ApplyT(func(v *ContainerAwsCluster) ContainerAwsClusterNetworkingOutput { return v.Networking }).(ContainerAwsClusterNetworkingOutput)
}

// The project for the resource
func (o ContainerAwsClusterOutput) Project() pulumi.StringOutput {
	return o.ApplyT(func(v *ContainerAwsCluster) pulumi.StringOutput { return v.Project }).(pulumi.StringOutput)
}

// Output only. If set, there are currently changes in flight to the cluster.
func (o ContainerAwsClusterOutput) Reconciling() pulumi.BoolOutput {
	return o.ApplyT(func(v *ContainerAwsCluster) pulumi.BoolOutput { return v.Reconciling }).(pulumi.BoolOutput)
}

// Output only. The current state of the cluster. Possible values: STATE_UNSPECIFIED, PROVISIONING, RUNNING, RECONCILING,
// STOPPING, ERROR, DEGRADED
func (o ContainerAwsClusterOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *ContainerAwsCluster) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

func (o ContainerAwsClusterOutput) Timeouts() ContainerAwsClusterTimeoutsPtrOutput {
	return o.ApplyT(func(v *ContainerAwsCluster) ContainerAwsClusterTimeoutsPtrOutput { return v.Timeouts }).(ContainerAwsClusterTimeoutsPtrOutput)
}

// Output only. A globally unique identifier for the cluster.
func (o ContainerAwsClusterOutput) Uid() pulumi.StringOutput {
	return o.ApplyT(func(v *ContainerAwsCluster) pulumi.StringOutput { return v.Uid }).(pulumi.StringOutput)
}

// Output only. The time at which this cluster was last updated.
func (o ContainerAwsClusterOutput) UpdateTime() pulumi.StringOutput {
	return o.ApplyT(func(v *ContainerAwsCluster) pulumi.StringOutput { return v.UpdateTime }).(pulumi.StringOutput)
}

// Output only. Workload Identity settings.
func (o ContainerAwsClusterOutput) WorkloadIdentityConfigs() ContainerAwsClusterWorkloadIdentityConfigArrayOutput {
	return o.ApplyT(func(v *ContainerAwsCluster) ContainerAwsClusterWorkloadIdentityConfigArrayOutput {
		return v.WorkloadIdentityConfigs
	}).(ContainerAwsClusterWorkloadIdentityConfigArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ContainerAwsClusterInput)(nil)).Elem(), &ContainerAwsCluster{})
	pulumi.RegisterOutputType(ContainerAwsClusterOutput{})
}
