// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package googlebeta

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/google-beta/v6/google-beta/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupBackupDrBackupPlan(ctx *pulumi.Context, args *LookupBackupDrBackupPlanArgs, opts ...pulumi.InvokeOption) (*LookupBackupDrBackupPlanResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupBackupDrBackupPlanResult
	err = ctx.InvokePackage("google-beta:index/getBackupDrBackupPlan:getBackupDrBackupPlan", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getBackupDrBackupPlan.
type LookupBackupDrBackupPlanArgs struct {
	BackupPlanId string  `pulumi:"backupPlanId"`
	Id           *string `pulumi:"id"`
	Location     string  `pulumi:"location"`
	Project      *string `pulumi:"project"`
}

// A collection of values returned by getBackupDrBackupPlan.
type LookupBackupDrBackupPlanResult struct {
	BackupPlanId              string                            `pulumi:"backupPlanId"`
	BackupRules               []GetBackupDrBackupPlanBackupRule `pulumi:"backupRules"`
	BackupVault               string                            `pulumi:"backupVault"`
	BackupVaultServiceAccount string                            `pulumi:"backupVaultServiceAccount"`
	CreateTime                string                            `pulumi:"createTime"`
	Description               string                            `pulumi:"description"`
	Id                        string                            `pulumi:"id"`
	Location                  string                            `pulumi:"location"`
	Name                      string                            `pulumi:"name"`
	Project                   *string                           `pulumi:"project"`
	ResourceType              string                            `pulumi:"resourceType"`
	UpdateTime                string                            `pulumi:"updateTime"`
}

func LookupBackupDrBackupPlanOutput(ctx *pulumi.Context, args LookupBackupDrBackupPlanOutputArgs, opts ...pulumi.InvokeOption) LookupBackupDrBackupPlanResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupBackupDrBackupPlanResultOutput, error) {
			args := v.(LookupBackupDrBackupPlanArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupBackupDrBackupPlanResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("google-beta:index/getBackupDrBackupPlan:getBackupDrBackupPlan", args, LookupBackupDrBackupPlanResultOutput{}, options).(LookupBackupDrBackupPlanResultOutput), nil
		}).(LookupBackupDrBackupPlanResultOutput)
}

// A collection of arguments for invoking getBackupDrBackupPlan.
type LookupBackupDrBackupPlanOutputArgs struct {
	BackupPlanId pulumi.StringInput    `pulumi:"backupPlanId"`
	Id           pulumi.StringPtrInput `pulumi:"id"`
	Location     pulumi.StringInput    `pulumi:"location"`
	Project      pulumi.StringPtrInput `pulumi:"project"`
}

func (LookupBackupDrBackupPlanOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupBackupDrBackupPlanArgs)(nil)).Elem()
}

// A collection of values returned by getBackupDrBackupPlan.
type LookupBackupDrBackupPlanResultOutput struct{ *pulumi.OutputState }

func (LookupBackupDrBackupPlanResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupBackupDrBackupPlanResult)(nil)).Elem()
}

func (o LookupBackupDrBackupPlanResultOutput) ToLookupBackupDrBackupPlanResultOutput() LookupBackupDrBackupPlanResultOutput {
	return o
}

func (o LookupBackupDrBackupPlanResultOutput) ToLookupBackupDrBackupPlanResultOutputWithContext(ctx context.Context) LookupBackupDrBackupPlanResultOutput {
	return o
}

func (o LookupBackupDrBackupPlanResultOutput) BackupPlanId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBackupDrBackupPlanResult) string { return v.BackupPlanId }).(pulumi.StringOutput)
}

func (o LookupBackupDrBackupPlanResultOutput) BackupRules() GetBackupDrBackupPlanBackupRuleArrayOutput {
	return o.ApplyT(func(v LookupBackupDrBackupPlanResult) []GetBackupDrBackupPlanBackupRule { return v.BackupRules }).(GetBackupDrBackupPlanBackupRuleArrayOutput)
}

func (o LookupBackupDrBackupPlanResultOutput) BackupVault() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBackupDrBackupPlanResult) string { return v.BackupVault }).(pulumi.StringOutput)
}

func (o LookupBackupDrBackupPlanResultOutput) BackupVaultServiceAccount() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBackupDrBackupPlanResult) string { return v.BackupVaultServiceAccount }).(pulumi.StringOutput)
}

func (o LookupBackupDrBackupPlanResultOutput) CreateTime() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBackupDrBackupPlanResult) string { return v.CreateTime }).(pulumi.StringOutput)
}

func (o LookupBackupDrBackupPlanResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBackupDrBackupPlanResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupBackupDrBackupPlanResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBackupDrBackupPlanResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupBackupDrBackupPlanResultOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBackupDrBackupPlanResult) string { return v.Location }).(pulumi.StringOutput)
}

func (o LookupBackupDrBackupPlanResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBackupDrBackupPlanResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupBackupDrBackupPlanResultOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupBackupDrBackupPlanResult) *string { return v.Project }).(pulumi.StringPtrOutput)
}

func (o LookupBackupDrBackupPlanResultOutput) ResourceType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBackupDrBackupPlanResult) string { return v.ResourceType }).(pulumi.StringOutput)
}

func (o LookupBackupDrBackupPlanResultOutput) UpdateTime() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBackupDrBackupPlanResult) string { return v.UpdateTime }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupBackupDrBackupPlanResultOutput{})
}
