// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package googlebeta

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/google-beta/v6/google-beta/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupComputeInstanceTemplate(ctx *pulumi.Context, args *LookupComputeInstanceTemplateArgs, opts ...pulumi.InvokeOption) (*LookupComputeInstanceTemplateResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupComputeInstanceTemplateResult
	err = ctx.InvokePackage("google-beta:index/getComputeInstanceTemplate:getComputeInstanceTemplate", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getComputeInstanceTemplate.
type LookupComputeInstanceTemplateArgs struct {
	Filter         *string `pulumi:"filter"`
	Id             *string `pulumi:"id"`
	MostRecent     *bool   `pulumi:"mostRecent"`
	Name           *string `pulumi:"name"`
	Project        *string `pulumi:"project"`
	SelfLinkUnique *string `pulumi:"selfLinkUnique"`
}

// A collection of values returned by getComputeInstanceTemplate.
type LookupComputeInstanceTemplateResult struct {
	AdvancedMachineFeatures     []GetComputeInstanceTemplateAdvancedMachineFeature     `pulumi:"advancedMachineFeatures"`
	CanIpForward                bool                                                   `pulumi:"canIpForward"`
	ConfidentialInstanceConfigs []GetComputeInstanceTemplateConfidentialInstanceConfig `pulumi:"confidentialInstanceConfigs"`
	CreationTimestamp           string                                                 `pulumi:"creationTimestamp"`
	Description                 string                                                 `pulumi:"description"`
	Disks                       []GetComputeInstanceTemplateDisk                       `pulumi:"disks"`
	EffectiveLabels             map[string]string                                      `pulumi:"effectiveLabels"`
	EnableDisplay               bool                                                   `pulumi:"enableDisplay"`
	Filter                      *string                                                `pulumi:"filter"`
	GuestAccelerators           []GetComputeInstanceTemplateGuestAccelerator           `pulumi:"guestAccelerators"`
	Id                          string                                                 `pulumi:"id"`
	InstanceDescription         string                                                 `pulumi:"instanceDescription"`
	KeyRevocationActionType     string                                                 `pulumi:"keyRevocationActionType"`
	Labels                      map[string]string                                      `pulumi:"labels"`
	MachineType                 string                                                 `pulumi:"machineType"`
	Metadata                    map[string]string                                      `pulumi:"metadata"`
	MetadataFingerprint         string                                                 `pulumi:"metadataFingerprint"`
	MetadataStartupScript       string                                                 `pulumi:"metadataStartupScript"`
	MinCpuPlatform              string                                                 `pulumi:"minCpuPlatform"`
	MostRecent                  *bool                                                  `pulumi:"mostRecent"`
	Name                        *string                                                `pulumi:"name"`
	NamePrefix                  string                                                 `pulumi:"namePrefix"`
	NetworkInterfaces           []GetComputeInstanceTemplateNetworkInterface           `pulumi:"networkInterfaces"`
	NetworkPerformanceConfigs   []GetComputeInstanceTemplateNetworkPerformanceConfig   `pulumi:"networkPerformanceConfigs"`
	PartnerMetadata             map[string]string                                      `pulumi:"partnerMetadata"`
	Project                     *string                                                `pulumi:"project"`
	Region                      string                                                 `pulumi:"region"`
	ReservationAffinities       []GetComputeInstanceTemplateReservationAffinity        `pulumi:"reservationAffinities"`
	ResourceManagerTags         map[string]string                                      `pulumi:"resourceManagerTags"`
	ResourcePolicies            []string                                               `pulumi:"resourcePolicies"`
	Schedulings                 []GetComputeInstanceTemplateScheduling                 `pulumi:"schedulings"`
	SelfLink                    string                                                 `pulumi:"selfLink"`
	SelfLinkUnique              *string                                                `pulumi:"selfLinkUnique"`
	ServiceAccounts             []GetComputeInstanceTemplateServiceAccount             `pulumi:"serviceAccounts"`
	ShieldedInstanceConfigs     []GetComputeInstanceTemplateShieldedInstanceConfig     `pulumi:"shieldedInstanceConfigs"`
	Tags                        []string                                               `pulumi:"tags"`
	TagsFingerprint             string                                                 `pulumi:"tagsFingerprint"`
	TerraformLabels             map[string]string                                      `pulumi:"terraformLabels"`
}

func LookupComputeInstanceTemplateOutput(ctx *pulumi.Context, args LookupComputeInstanceTemplateOutputArgs, opts ...pulumi.InvokeOption) LookupComputeInstanceTemplateResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupComputeInstanceTemplateResultOutput, error) {
			args := v.(LookupComputeInstanceTemplateArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupComputeInstanceTemplateResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("google-beta:index/getComputeInstanceTemplate:getComputeInstanceTemplate", args, LookupComputeInstanceTemplateResultOutput{}, options).(LookupComputeInstanceTemplateResultOutput), nil
		}).(LookupComputeInstanceTemplateResultOutput)
}

// A collection of arguments for invoking getComputeInstanceTemplate.
type LookupComputeInstanceTemplateOutputArgs struct {
	Filter         pulumi.StringPtrInput `pulumi:"filter"`
	Id             pulumi.StringPtrInput `pulumi:"id"`
	MostRecent     pulumi.BoolPtrInput   `pulumi:"mostRecent"`
	Name           pulumi.StringPtrInput `pulumi:"name"`
	Project        pulumi.StringPtrInput `pulumi:"project"`
	SelfLinkUnique pulumi.StringPtrInput `pulumi:"selfLinkUnique"`
}

func (LookupComputeInstanceTemplateOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupComputeInstanceTemplateArgs)(nil)).Elem()
}

// A collection of values returned by getComputeInstanceTemplate.
type LookupComputeInstanceTemplateResultOutput struct{ *pulumi.OutputState }

func (LookupComputeInstanceTemplateResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupComputeInstanceTemplateResult)(nil)).Elem()
}

func (o LookupComputeInstanceTemplateResultOutput) ToLookupComputeInstanceTemplateResultOutput() LookupComputeInstanceTemplateResultOutput {
	return o
}

func (o LookupComputeInstanceTemplateResultOutput) ToLookupComputeInstanceTemplateResultOutputWithContext(ctx context.Context) LookupComputeInstanceTemplateResultOutput {
	return o
}

func (o LookupComputeInstanceTemplateResultOutput) AdvancedMachineFeatures() GetComputeInstanceTemplateAdvancedMachineFeatureArrayOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) []GetComputeInstanceTemplateAdvancedMachineFeature {
		return v.AdvancedMachineFeatures
	}).(GetComputeInstanceTemplateAdvancedMachineFeatureArrayOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) CanIpForward() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) bool { return v.CanIpForward }).(pulumi.BoolOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) ConfidentialInstanceConfigs() GetComputeInstanceTemplateConfidentialInstanceConfigArrayOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) []GetComputeInstanceTemplateConfidentialInstanceConfig {
		return v.ConfidentialInstanceConfigs
	}).(GetComputeInstanceTemplateConfidentialInstanceConfigArrayOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) CreationTimestamp() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) string { return v.CreationTimestamp }).(pulumi.StringOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) Disks() GetComputeInstanceTemplateDiskArrayOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) []GetComputeInstanceTemplateDisk { return v.Disks }).(GetComputeInstanceTemplateDiskArrayOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) EffectiveLabels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) map[string]string { return v.EffectiveLabels }).(pulumi.StringMapOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) EnableDisplay() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) bool { return v.EnableDisplay }).(pulumi.BoolOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) Filter() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) *string { return v.Filter }).(pulumi.StringPtrOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) GuestAccelerators() GetComputeInstanceTemplateGuestAcceleratorArrayOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) []GetComputeInstanceTemplateGuestAccelerator {
		return v.GuestAccelerators
	}).(GetComputeInstanceTemplateGuestAcceleratorArrayOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) InstanceDescription() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) string { return v.InstanceDescription }).(pulumi.StringOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) KeyRevocationActionType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) string { return v.KeyRevocationActionType }).(pulumi.StringOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) MachineType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) string { return v.MachineType }).(pulumi.StringOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) Metadata() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) map[string]string { return v.Metadata }).(pulumi.StringMapOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) MetadataFingerprint() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) string { return v.MetadataFingerprint }).(pulumi.StringOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) MetadataStartupScript() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) string { return v.MetadataStartupScript }).(pulumi.StringOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) MinCpuPlatform() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) string { return v.MinCpuPlatform }).(pulumi.StringOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) MostRecent() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) *bool { return v.MostRecent }).(pulumi.BoolPtrOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) NamePrefix() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) string { return v.NamePrefix }).(pulumi.StringOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) NetworkInterfaces() GetComputeInstanceTemplateNetworkInterfaceArrayOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) []GetComputeInstanceTemplateNetworkInterface {
		return v.NetworkInterfaces
	}).(GetComputeInstanceTemplateNetworkInterfaceArrayOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) NetworkPerformanceConfigs() GetComputeInstanceTemplateNetworkPerformanceConfigArrayOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) []GetComputeInstanceTemplateNetworkPerformanceConfig {
		return v.NetworkPerformanceConfigs
	}).(GetComputeInstanceTemplateNetworkPerformanceConfigArrayOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) PartnerMetadata() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) map[string]string { return v.PartnerMetadata }).(pulumi.StringMapOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) *string { return v.Project }).(pulumi.StringPtrOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) string { return v.Region }).(pulumi.StringOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) ReservationAffinities() GetComputeInstanceTemplateReservationAffinityArrayOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) []GetComputeInstanceTemplateReservationAffinity {
		return v.ReservationAffinities
	}).(GetComputeInstanceTemplateReservationAffinityArrayOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) ResourceManagerTags() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) map[string]string { return v.ResourceManagerTags }).(pulumi.StringMapOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) ResourcePolicies() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) []string { return v.ResourcePolicies }).(pulumi.StringArrayOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) Schedulings() GetComputeInstanceTemplateSchedulingArrayOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) []GetComputeInstanceTemplateScheduling {
		return v.Schedulings
	}).(GetComputeInstanceTemplateSchedulingArrayOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) SelfLink() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) string { return v.SelfLink }).(pulumi.StringOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) SelfLinkUnique() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) *string { return v.SelfLinkUnique }).(pulumi.StringPtrOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) ServiceAccounts() GetComputeInstanceTemplateServiceAccountArrayOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) []GetComputeInstanceTemplateServiceAccount {
		return v.ServiceAccounts
	}).(GetComputeInstanceTemplateServiceAccountArrayOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) ShieldedInstanceConfigs() GetComputeInstanceTemplateShieldedInstanceConfigArrayOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) []GetComputeInstanceTemplateShieldedInstanceConfig {
		return v.ShieldedInstanceConfigs
	}).(GetComputeInstanceTemplateShieldedInstanceConfigArrayOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) []string { return v.Tags }).(pulumi.StringArrayOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) TagsFingerprint() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) string { return v.TagsFingerprint }).(pulumi.StringOutput)
}

func (o LookupComputeInstanceTemplateResultOutput) TerraformLabels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupComputeInstanceTemplateResult) map[string]string { return v.TerraformLabels }).(pulumi.StringMapOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupComputeInstanceTemplateResultOutput{})
}
