// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package googlebeta

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/google-beta/v6/google-beta/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type IapClient struct {
	pulumi.CustomResourceState

	// Identifier of the brand to which this client is attached to. The format is
	// 'projects/{project_number}/brands/{brand_id}'.
	Brand pulumi.StringOutput `pulumi:"brand"`
	// Output only. Unique identifier of the OAuth client.
	ClientId pulumi.StringOutput `pulumi:"clientId"`
	// Human-friendly name given to the OAuth client.
	DisplayName pulumi.StringOutput `pulumi:"displayName"`
	IapClientId pulumi.StringOutput `pulumi:"iapClientId"`
	// Output only. Client secret of the OAuth client.
	Secret   pulumi.StringOutput        `pulumi:"secret"`
	Timeouts IapClientTimeoutsPtrOutput `pulumi:"timeouts"`
}

// NewIapClient registers a new resource with the given unique name, arguments, and options.
func NewIapClient(ctx *pulumi.Context,
	name string, args *IapClientArgs, opts ...pulumi.ResourceOption) (*IapClient, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Brand == nil {
		return nil, errors.New("invalid value for required argument 'Brand'")
	}
	if args.DisplayName == nil {
		return nil, errors.New("invalid value for required argument 'DisplayName'")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"secret",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource IapClient
	err = ctx.RegisterPackageResource("google-beta:index/iapClient:IapClient", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetIapClient gets an existing IapClient resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetIapClient(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *IapClientState, opts ...pulumi.ResourceOption) (*IapClient, error) {
	var resource IapClient
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("google-beta:index/iapClient:IapClient", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering IapClient resources.
type iapClientState struct {
	// Identifier of the brand to which this client is attached to. The format is
	// 'projects/{project_number}/brands/{brand_id}'.
	Brand *string `pulumi:"brand"`
	// Output only. Unique identifier of the OAuth client.
	ClientId *string `pulumi:"clientId"`
	// Human-friendly name given to the OAuth client.
	DisplayName *string `pulumi:"displayName"`
	IapClientId *string `pulumi:"iapClientId"`
	// Output only. Client secret of the OAuth client.
	Secret   *string            `pulumi:"secret"`
	Timeouts *IapClientTimeouts `pulumi:"timeouts"`
}

type IapClientState struct {
	// Identifier of the brand to which this client is attached to. The format is
	// 'projects/{project_number}/brands/{brand_id}'.
	Brand pulumi.StringPtrInput
	// Output only. Unique identifier of the OAuth client.
	ClientId pulumi.StringPtrInput
	// Human-friendly name given to the OAuth client.
	DisplayName pulumi.StringPtrInput
	IapClientId pulumi.StringPtrInput
	// Output only. Client secret of the OAuth client.
	Secret   pulumi.StringPtrInput
	Timeouts IapClientTimeoutsPtrInput
}

func (IapClientState) ElementType() reflect.Type {
	return reflect.TypeOf((*iapClientState)(nil)).Elem()
}

type iapClientArgs struct {
	// Identifier of the brand to which this client is attached to. The format is
	// 'projects/{project_number}/brands/{brand_id}'.
	Brand string `pulumi:"brand"`
	// Human-friendly name given to the OAuth client.
	DisplayName string             `pulumi:"displayName"`
	IapClientId *string            `pulumi:"iapClientId"`
	Timeouts    *IapClientTimeouts `pulumi:"timeouts"`
}

// The set of arguments for constructing a IapClient resource.
type IapClientArgs struct {
	// Identifier of the brand to which this client is attached to. The format is
	// 'projects/{project_number}/brands/{brand_id}'.
	Brand pulumi.StringInput
	// Human-friendly name given to the OAuth client.
	DisplayName pulumi.StringInput
	IapClientId pulumi.StringPtrInput
	Timeouts    IapClientTimeoutsPtrInput
}

func (IapClientArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*iapClientArgs)(nil)).Elem()
}

type IapClientInput interface {
	pulumi.Input

	ToIapClientOutput() IapClientOutput
	ToIapClientOutputWithContext(ctx context.Context) IapClientOutput
}

func (*IapClient) ElementType() reflect.Type {
	return reflect.TypeOf((**IapClient)(nil)).Elem()
}

func (i *IapClient) ToIapClientOutput() IapClientOutput {
	return i.ToIapClientOutputWithContext(context.Background())
}

func (i *IapClient) ToIapClientOutputWithContext(ctx context.Context) IapClientOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IapClientOutput)
}

type IapClientOutput struct{ *pulumi.OutputState }

func (IapClientOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**IapClient)(nil)).Elem()
}

func (o IapClientOutput) ToIapClientOutput() IapClientOutput {
	return o
}

func (o IapClientOutput) ToIapClientOutputWithContext(ctx context.Context) IapClientOutput {
	return o
}

// Identifier of the brand to which this client is attached to. The format is
// 'projects/{project_number}/brands/{brand_id}'.
func (o IapClientOutput) Brand() pulumi.StringOutput {
	return o.ApplyT(func(v *IapClient) pulumi.StringOutput { return v.Brand }).(pulumi.StringOutput)
}

// Output only. Unique identifier of the OAuth client.
func (o IapClientOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v *IapClient) pulumi.StringOutput { return v.ClientId }).(pulumi.StringOutput)
}

// Human-friendly name given to the OAuth client.
func (o IapClientOutput) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v *IapClient) pulumi.StringOutput { return v.DisplayName }).(pulumi.StringOutput)
}

func (o IapClientOutput) IapClientId() pulumi.StringOutput {
	return o.ApplyT(func(v *IapClient) pulumi.StringOutput { return v.IapClientId }).(pulumi.StringOutput)
}

// Output only. Client secret of the OAuth client.
func (o IapClientOutput) Secret() pulumi.StringOutput {
	return o.ApplyT(func(v *IapClient) pulumi.StringOutput { return v.Secret }).(pulumi.StringOutput)
}

func (o IapClientOutput) Timeouts() IapClientTimeoutsPtrOutput {
	return o.ApplyT(func(v *IapClient) IapClientTimeoutsPtrOutput { return v.Timeouts }).(IapClientTimeoutsPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*IapClientInput)(nil)).Elem(), &IapClient{})
	pulumi.RegisterOutputType(IapClientOutput{})
}
