// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package googlebeta

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/google-beta/v6/google-beta/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type MlEngineModel struct {
	pulumi.CustomResourceState

	// The default version of the model. This version will be used to handle prediction requests that do not specify a version.
	DefaultVersion MlEngineModelDefaultVersionPtrOutput `pulumi:"defaultVersion"`
	// The description specified for the model when it was created.
	Description     pulumi.StringPtrOutput `pulumi:"description"`
	EffectiveLabels pulumi.StringMapOutput `pulumi:"effectiveLabels"`
	// One or more labels that you can add, to organize your models. **Note**: This field is non-authoritative, and will only
	// manage the labels present in your configuration. Please refer to the field 'effective_labels' for all of the labels
	// present on the resource.
	Labels          pulumi.StringMapOutput `pulumi:"labels"`
	MlEngineModelId pulumi.StringOutput    `pulumi:"mlEngineModelId"`
	// The name specified for the model.
	Name pulumi.StringOutput `pulumi:"name"`
	// If true, online prediction nodes send stderr and stdout streams to Stackdriver Logging
	OnlinePredictionConsoleLogging pulumi.BoolPtrOutput `pulumi:"onlinePredictionConsoleLogging"`
	// If true, online prediction access logs are sent to StackDriver Logging.
	OnlinePredictionLogging pulumi.BoolPtrOutput `pulumi:"onlinePredictionLogging"`
	Project                 pulumi.StringOutput  `pulumi:"project"`
	// The list of regions where the model is going to be deployed. Currently only one region per model is supported
	Regions pulumi.StringArrayOutput `pulumi:"regions"`
	// The combination of labels configured directly on the resource and default labels configured on the provider.
	TerraformLabels pulumi.StringMapOutput         `pulumi:"terraformLabels"`
	Timeouts        MlEngineModelTimeoutsPtrOutput `pulumi:"timeouts"`
}

// NewMlEngineModel registers a new resource with the given unique name, arguments, and options.
func NewMlEngineModel(ctx *pulumi.Context,
	name string, args *MlEngineModelArgs, opts ...pulumi.ResourceOption) (*MlEngineModel, error) {
	if args == nil {
		args = &MlEngineModelArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource MlEngineModel
	err = ctx.RegisterPackageResource("google-beta:index/mlEngineModel:MlEngineModel", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetMlEngineModel gets an existing MlEngineModel resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetMlEngineModel(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *MlEngineModelState, opts ...pulumi.ResourceOption) (*MlEngineModel, error) {
	var resource MlEngineModel
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("google-beta:index/mlEngineModel:MlEngineModel", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering MlEngineModel resources.
type mlEngineModelState struct {
	// The default version of the model. This version will be used to handle prediction requests that do not specify a version.
	DefaultVersion *MlEngineModelDefaultVersion `pulumi:"defaultVersion"`
	// The description specified for the model when it was created.
	Description     *string           `pulumi:"description"`
	EffectiveLabels map[string]string `pulumi:"effectiveLabels"`
	// One or more labels that you can add, to organize your models. **Note**: This field is non-authoritative, and will only
	// manage the labels present in your configuration. Please refer to the field 'effective_labels' for all of the labels
	// present on the resource.
	Labels          map[string]string `pulumi:"labels"`
	MlEngineModelId *string           `pulumi:"mlEngineModelId"`
	// The name specified for the model.
	Name *string `pulumi:"name"`
	// If true, online prediction nodes send stderr and stdout streams to Stackdriver Logging
	OnlinePredictionConsoleLogging *bool `pulumi:"onlinePredictionConsoleLogging"`
	// If true, online prediction access logs are sent to StackDriver Logging.
	OnlinePredictionLogging *bool   `pulumi:"onlinePredictionLogging"`
	Project                 *string `pulumi:"project"`
	// The list of regions where the model is going to be deployed. Currently only one region per model is supported
	Regions []string `pulumi:"regions"`
	// The combination of labels configured directly on the resource and default labels configured on the provider.
	TerraformLabels map[string]string      `pulumi:"terraformLabels"`
	Timeouts        *MlEngineModelTimeouts `pulumi:"timeouts"`
}

type MlEngineModelState struct {
	// The default version of the model. This version will be used to handle prediction requests that do not specify a version.
	DefaultVersion MlEngineModelDefaultVersionPtrInput
	// The description specified for the model when it was created.
	Description     pulumi.StringPtrInput
	EffectiveLabels pulumi.StringMapInput
	// One or more labels that you can add, to organize your models. **Note**: This field is non-authoritative, and will only
	// manage the labels present in your configuration. Please refer to the field 'effective_labels' for all of the labels
	// present on the resource.
	Labels          pulumi.StringMapInput
	MlEngineModelId pulumi.StringPtrInput
	// The name specified for the model.
	Name pulumi.StringPtrInput
	// If true, online prediction nodes send stderr and stdout streams to Stackdriver Logging
	OnlinePredictionConsoleLogging pulumi.BoolPtrInput
	// If true, online prediction access logs are sent to StackDriver Logging.
	OnlinePredictionLogging pulumi.BoolPtrInput
	Project                 pulumi.StringPtrInput
	// The list of regions where the model is going to be deployed. Currently only one region per model is supported
	Regions pulumi.StringArrayInput
	// The combination of labels configured directly on the resource and default labels configured on the provider.
	TerraformLabels pulumi.StringMapInput
	Timeouts        MlEngineModelTimeoutsPtrInput
}

func (MlEngineModelState) ElementType() reflect.Type {
	return reflect.TypeOf((*mlEngineModelState)(nil)).Elem()
}

type mlEngineModelArgs struct {
	// The default version of the model. This version will be used to handle prediction requests that do not specify a version.
	DefaultVersion *MlEngineModelDefaultVersion `pulumi:"defaultVersion"`
	// The description specified for the model when it was created.
	Description *string `pulumi:"description"`
	// One or more labels that you can add, to organize your models. **Note**: This field is non-authoritative, and will only
	// manage the labels present in your configuration. Please refer to the field 'effective_labels' for all of the labels
	// present on the resource.
	Labels          map[string]string `pulumi:"labels"`
	MlEngineModelId *string           `pulumi:"mlEngineModelId"`
	// The name specified for the model.
	Name *string `pulumi:"name"`
	// If true, online prediction nodes send stderr and stdout streams to Stackdriver Logging
	OnlinePredictionConsoleLogging *bool `pulumi:"onlinePredictionConsoleLogging"`
	// If true, online prediction access logs are sent to StackDriver Logging.
	OnlinePredictionLogging *bool   `pulumi:"onlinePredictionLogging"`
	Project                 *string `pulumi:"project"`
	// The list of regions where the model is going to be deployed. Currently only one region per model is supported
	Regions  []string               `pulumi:"regions"`
	Timeouts *MlEngineModelTimeouts `pulumi:"timeouts"`
}

// The set of arguments for constructing a MlEngineModel resource.
type MlEngineModelArgs struct {
	// The default version of the model. This version will be used to handle prediction requests that do not specify a version.
	DefaultVersion MlEngineModelDefaultVersionPtrInput
	// The description specified for the model when it was created.
	Description pulumi.StringPtrInput
	// One or more labels that you can add, to organize your models. **Note**: This field is non-authoritative, and will only
	// manage the labels present in your configuration. Please refer to the field 'effective_labels' for all of the labels
	// present on the resource.
	Labels          pulumi.StringMapInput
	MlEngineModelId pulumi.StringPtrInput
	// The name specified for the model.
	Name pulumi.StringPtrInput
	// If true, online prediction nodes send stderr and stdout streams to Stackdriver Logging
	OnlinePredictionConsoleLogging pulumi.BoolPtrInput
	// If true, online prediction access logs are sent to StackDriver Logging.
	OnlinePredictionLogging pulumi.BoolPtrInput
	Project                 pulumi.StringPtrInput
	// The list of regions where the model is going to be deployed. Currently only one region per model is supported
	Regions  pulumi.StringArrayInput
	Timeouts MlEngineModelTimeoutsPtrInput
}

func (MlEngineModelArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*mlEngineModelArgs)(nil)).Elem()
}

type MlEngineModelInput interface {
	pulumi.Input

	ToMlEngineModelOutput() MlEngineModelOutput
	ToMlEngineModelOutputWithContext(ctx context.Context) MlEngineModelOutput
}

func (*MlEngineModel) ElementType() reflect.Type {
	return reflect.TypeOf((**MlEngineModel)(nil)).Elem()
}

func (i *MlEngineModel) ToMlEngineModelOutput() MlEngineModelOutput {
	return i.ToMlEngineModelOutputWithContext(context.Background())
}

func (i *MlEngineModel) ToMlEngineModelOutputWithContext(ctx context.Context) MlEngineModelOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MlEngineModelOutput)
}

type MlEngineModelOutput struct{ *pulumi.OutputState }

func (MlEngineModelOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**MlEngineModel)(nil)).Elem()
}

func (o MlEngineModelOutput) ToMlEngineModelOutput() MlEngineModelOutput {
	return o
}

func (o MlEngineModelOutput) ToMlEngineModelOutputWithContext(ctx context.Context) MlEngineModelOutput {
	return o
}

// The default version of the model. This version will be used to handle prediction requests that do not specify a version.
func (o MlEngineModelOutput) DefaultVersion() MlEngineModelDefaultVersionPtrOutput {
	return o.ApplyT(func(v *MlEngineModel) MlEngineModelDefaultVersionPtrOutput { return v.DefaultVersion }).(MlEngineModelDefaultVersionPtrOutput)
}

// The description specified for the model when it was created.
func (o MlEngineModelOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *MlEngineModel) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

func (o MlEngineModelOutput) EffectiveLabels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *MlEngineModel) pulumi.StringMapOutput { return v.EffectiveLabels }).(pulumi.StringMapOutput)
}

// One or more labels that you can add, to organize your models. **Note**: This field is non-authoritative, and will only
// manage the labels present in your configuration. Please refer to the field 'effective_labels' for all of the labels
// present on the resource.
func (o MlEngineModelOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *MlEngineModel) pulumi.StringMapOutput { return v.Labels }).(pulumi.StringMapOutput)
}

func (o MlEngineModelOutput) MlEngineModelId() pulumi.StringOutput {
	return o.ApplyT(func(v *MlEngineModel) pulumi.StringOutput { return v.MlEngineModelId }).(pulumi.StringOutput)
}

// The name specified for the model.
func (o MlEngineModelOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *MlEngineModel) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// If true, online prediction nodes send stderr and stdout streams to Stackdriver Logging
func (o MlEngineModelOutput) OnlinePredictionConsoleLogging() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *MlEngineModel) pulumi.BoolPtrOutput { return v.OnlinePredictionConsoleLogging }).(pulumi.BoolPtrOutput)
}

// If true, online prediction access logs are sent to StackDriver Logging.
func (o MlEngineModelOutput) OnlinePredictionLogging() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *MlEngineModel) pulumi.BoolPtrOutput { return v.OnlinePredictionLogging }).(pulumi.BoolPtrOutput)
}

func (o MlEngineModelOutput) Project() pulumi.StringOutput {
	return o.ApplyT(func(v *MlEngineModel) pulumi.StringOutput { return v.Project }).(pulumi.StringOutput)
}

// The list of regions where the model is going to be deployed. Currently only one region per model is supported
func (o MlEngineModelOutput) Regions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *MlEngineModel) pulumi.StringArrayOutput { return v.Regions }).(pulumi.StringArrayOutput)
}

// The combination of labels configured directly on the resource and default labels configured on the provider.
func (o MlEngineModelOutput) TerraformLabels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *MlEngineModel) pulumi.StringMapOutput { return v.TerraformLabels }).(pulumi.StringMapOutput)
}

func (o MlEngineModelOutput) Timeouts() MlEngineModelTimeoutsPtrOutput {
	return o.ApplyT(func(v *MlEngineModel) MlEngineModelTimeoutsPtrOutput { return v.Timeouts }).(MlEngineModelTimeoutsPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*MlEngineModelInput)(nil)).Elem(), &MlEngineModel{})
	pulumi.RegisterOutputType(MlEngineModelOutput{})
}
