// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package googlebeta

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/google-beta/v6/google-beta/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type WorkstationsWorkstationCluster struct {
	pulumi.CustomResourceState

	// Client-specified annotations. This is distinct from labels. **Note**: This field is non-authoritative, and will only
	// manage the annotations present in your configuration. Please refer to the field 'effective_annotations' for all of the
	// annotations present on the resource.
	Annotations pulumi.StringMapOutput `pulumi:"annotations"`
	// Status conditions describing the current resource state.
	Conditions WorkstationsWorkstationClusterConditionArrayOutput `pulumi:"conditions"`
	// The private IP address of the control plane for this workstation cluster. Workstation VMs need access to this IP address
	// to work with the service, so make sure that your firewall rules allow egress from the workstation VMs to this address.
	ControlPlaneIp pulumi.StringOutput `pulumi:"controlPlaneIp"`
	// Time when this resource was created.
	CreateTime pulumi.StringOutput `pulumi:"createTime"`
	// Whether this resource is in degraded mode, in which case it may require user action to restore full functionality.
	// Details can be found in the conditions field.
	Degraded pulumi.BoolOutput `pulumi:"degraded"`
	// Human-readable name for this resource.
	DisplayName pulumi.StringPtrOutput `pulumi:"displayName"`
	// Configuration options for a custom domain.
	DomainConfig         WorkstationsWorkstationClusterDomainConfigPtrOutput `pulumi:"domainConfig"`
	EffectiveAnnotations pulumi.StringMapOutput                              `pulumi:"effectiveAnnotations"`
	EffectiveLabels      pulumi.StringMapOutput                              `pulumi:"effectiveLabels"`
	// Checksum computed by the server. May be sent on update and delete requests to ensure that the client has an up-to-date
	// value before proceeding.
	Etag pulumi.StringOutput `pulumi:"etag"`
	// Client-specified labels that are applied to the resource and that are also propagated to the underlying Compute Engine
	// resources. **Note**: This field is non-authoritative, and will only manage the labels present in your configuration.
	// Please refer to the field 'effective_labels' for all of the labels present on the resource.
	Labels pulumi.StringMapOutput `pulumi:"labels"`
	// The location where the workstation cluster should reside.
	Location pulumi.StringPtrOutput `pulumi:"location"`
	// The name of the cluster resource.
	Name pulumi.StringOutput `pulumi:"name"`
	// The relative resource name of the VPC network on which the instance can be accessed. It is specified in the following
	// form: "projects/{projectNumber}/global/networks/{network_id}".
	Network pulumi.StringOutput `pulumi:"network"`
	// Configuration for private cluster.
	PrivateClusterConfig WorkstationsWorkstationClusterPrivateClusterConfigPtrOutput `pulumi:"privateClusterConfig"`
	Project              pulumi.StringOutput                                         `pulumi:"project"`
	// Name of the Compute Engine subnetwork in which instances associated with this cluster will be created. Must be part of
	// the subnetwork specified for this cluster.
	Subnetwork pulumi.StringOutput `pulumi:"subnetwork"`
	// The combination of labels configured directly on the resource and default labels configured on the provider.
	TerraformLabels pulumi.StringMapOutput                          `pulumi:"terraformLabels"`
	Timeouts        WorkstationsWorkstationClusterTimeoutsPtrOutput `pulumi:"timeouts"`
	// The system-generated UID of the resource.
	Uid pulumi.StringOutput `pulumi:"uid"`
	// ID to use for the workstation cluster.
	WorkstationClusterId             pulumi.StringOutput `pulumi:"workstationClusterId"`
	WorkstationsWorkstationClusterId pulumi.StringOutput `pulumi:"workstationsWorkstationClusterId"`
}

// NewWorkstationsWorkstationCluster registers a new resource with the given unique name, arguments, and options.
func NewWorkstationsWorkstationCluster(ctx *pulumi.Context,
	name string, args *WorkstationsWorkstationClusterArgs, opts ...pulumi.ResourceOption) (*WorkstationsWorkstationCluster, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Network == nil {
		return nil, errors.New("invalid value for required argument 'Network'")
	}
	if args.Subnetwork == nil {
		return nil, errors.New("invalid value for required argument 'Subnetwork'")
	}
	if args.WorkstationClusterId == nil {
		return nil, errors.New("invalid value for required argument 'WorkstationClusterId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource WorkstationsWorkstationCluster
	err = ctx.RegisterPackageResource("google-beta:index/workstationsWorkstationCluster:WorkstationsWorkstationCluster", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetWorkstationsWorkstationCluster gets an existing WorkstationsWorkstationCluster resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetWorkstationsWorkstationCluster(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *WorkstationsWorkstationClusterState, opts ...pulumi.ResourceOption) (*WorkstationsWorkstationCluster, error) {
	var resource WorkstationsWorkstationCluster
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("google-beta:index/workstationsWorkstationCluster:WorkstationsWorkstationCluster", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering WorkstationsWorkstationCluster resources.
type workstationsWorkstationClusterState struct {
	// Client-specified annotations. This is distinct from labels. **Note**: This field is non-authoritative, and will only
	// manage the annotations present in your configuration. Please refer to the field 'effective_annotations' for all of the
	// annotations present on the resource.
	Annotations map[string]string `pulumi:"annotations"`
	// Status conditions describing the current resource state.
	Conditions []WorkstationsWorkstationClusterCondition `pulumi:"conditions"`
	// The private IP address of the control plane for this workstation cluster. Workstation VMs need access to this IP address
	// to work with the service, so make sure that your firewall rules allow egress from the workstation VMs to this address.
	ControlPlaneIp *string `pulumi:"controlPlaneIp"`
	// Time when this resource was created.
	CreateTime *string `pulumi:"createTime"`
	// Whether this resource is in degraded mode, in which case it may require user action to restore full functionality.
	// Details can be found in the conditions field.
	Degraded *bool `pulumi:"degraded"`
	// Human-readable name for this resource.
	DisplayName *string `pulumi:"displayName"`
	// Configuration options for a custom domain.
	DomainConfig         *WorkstationsWorkstationClusterDomainConfig `pulumi:"domainConfig"`
	EffectiveAnnotations map[string]string                           `pulumi:"effectiveAnnotations"`
	EffectiveLabels      map[string]string                           `pulumi:"effectiveLabels"`
	// Checksum computed by the server. May be sent on update and delete requests to ensure that the client has an up-to-date
	// value before proceeding.
	Etag *string `pulumi:"etag"`
	// Client-specified labels that are applied to the resource and that are also propagated to the underlying Compute Engine
	// resources. **Note**: This field is non-authoritative, and will only manage the labels present in your configuration.
	// Please refer to the field 'effective_labels' for all of the labels present on the resource.
	Labels map[string]string `pulumi:"labels"`
	// The location where the workstation cluster should reside.
	Location *string `pulumi:"location"`
	// The name of the cluster resource.
	Name *string `pulumi:"name"`
	// The relative resource name of the VPC network on which the instance can be accessed. It is specified in the following
	// form: "projects/{projectNumber}/global/networks/{network_id}".
	Network *string `pulumi:"network"`
	// Configuration for private cluster.
	PrivateClusterConfig *WorkstationsWorkstationClusterPrivateClusterConfig `pulumi:"privateClusterConfig"`
	Project              *string                                             `pulumi:"project"`
	// Name of the Compute Engine subnetwork in which instances associated with this cluster will be created. Must be part of
	// the subnetwork specified for this cluster.
	Subnetwork *string `pulumi:"subnetwork"`
	// The combination of labels configured directly on the resource and default labels configured on the provider.
	TerraformLabels map[string]string                       `pulumi:"terraformLabels"`
	Timeouts        *WorkstationsWorkstationClusterTimeouts `pulumi:"timeouts"`
	// The system-generated UID of the resource.
	Uid *string `pulumi:"uid"`
	// ID to use for the workstation cluster.
	WorkstationClusterId             *string `pulumi:"workstationClusterId"`
	WorkstationsWorkstationClusterId *string `pulumi:"workstationsWorkstationClusterId"`
}

type WorkstationsWorkstationClusterState struct {
	// Client-specified annotations. This is distinct from labels. **Note**: This field is non-authoritative, and will only
	// manage the annotations present in your configuration. Please refer to the field 'effective_annotations' for all of the
	// annotations present on the resource.
	Annotations pulumi.StringMapInput
	// Status conditions describing the current resource state.
	Conditions WorkstationsWorkstationClusterConditionArrayInput
	// The private IP address of the control plane for this workstation cluster. Workstation VMs need access to this IP address
	// to work with the service, so make sure that your firewall rules allow egress from the workstation VMs to this address.
	ControlPlaneIp pulumi.StringPtrInput
	// Time when this resource was created.
	CreateTime pulumi.StringPtrInput
	// Whether this resource is in degraded mode, in which case it may require user action to restore full functionality.
	// Details can be found in the conditions field.
	Degraded pulumi.BoolPtrInput
	// Human-readable name for this resource.
	DisplayName pulumi.StringPtrInput
	// Configuration options for a custom domain.
	DomainConfig         WorkstationsWorkstationClusterDomainConfigPtrInput
	EffectiveAnnotations pulumi.StringMapInput
	EffectiveLabels      pulumi.StringMapInput
	// Checksum computed by the server. May be sent on update and delete requests to ensure that the client has an up-to-date
	// value before proceeding.
	Etag pulumi.StringPtrInput
	// Client-specified labels that are applied to the resource and that are also propagated to the underlying Compute Engine
	// resources. **Note**: This field is non-authoritative, and will only manage the labels present in your configuration.
	// Please refer to the field 'effective_labels' for all of the labels present on the resource.
	Labels pulumi.StringMapInput
	// The location where the workstation cluster should reside.
	Location pulumi.StringPtrInput
	// The name of the cluster resource.
	Name pulumi.StringPtrInput
	// The relative resource name of the VPC network on which the instance can be accessed. It is specified in the following
	// form: "projects/{projectNumber}/global/networks/{network_id}".
	Network pulumi.StringPtrInput
	// Configuration for private cluster.
	PrivateClusterConfig WorkstationsWorkstationClusterPrivateClusterConfigPtrInput
	Project              pulumi.StringPtrInput
	// Name of the Compute Engine subnetwork in which instances associated with this cluster will be created. Must be part of
	// the subnetwork specified for this cluster.
	Subnetwork pulumi.StringPtrInput
	// The combination of labels configured directly on the resource and default labels configured on the provider.
	TerraformLabels pulumi.StringMapInput
	Timeouts        WorkstationsWorkstationClusterTimeoutsPtrInput
	// The system-generated UID of the resource.
	Uid pulumi.StringPtrInput
	// ID to use for the workstation cluster.
	WorkstationClusterId             pulumi.StringPtrInput
	WorkstationsWorkstationClusterId pulumi.StringPtrInput
}

func (WorkstationsWorkstationClusterState) ElementType() reflect.Type {
	return reflect.TypeOf((*workstationsWorkstationClusterState)(nil)).Elem()
}

type workstationsWorkstationClusterArgs struct {
	// Client-specified annotations. This is distinct from labels. **Note**: This field is non-authoritative, and will only
	// manage the annotations present in your configuration. Please refer to the field 'effective_annotations' for all of the
	// annotations present on the resource.
	Annotations map[string]string `pulumi:"annotations"`
	// Human-readable name for this resource.
	DisplayName *string `pulumi:"displayName"`
	// Configuration options for a custom domain.
	DomainConfig *WorkstationsWorkstationClusterDomainConfig `pulumi:"domainConfig"`
	// Client-specified labels that are applied to the resource and that are also propagated to the underlying Compute Engine
	// resources. **Note**: This field is non-authoritative, and will only manage the labels present in your configuration.
	// Please refer to the field 'effective_labels' for all of the labels present on the resource.
	Labels map[string]string `pulumi:"labels"`
	// The location where the workstation cluster should reside.
	Location *string `pulumi:"location"`
	// The relative resource name of the VPC network on which the instance can be accessed. It is specified in the following
	// form: "projects/{projectNumber}/global/networks/{network_id}".
	Network string `pulumi:"network"`
	// Configuration for private cluster.
	PrivateClusterConfig *WorkstationsWorkstationClusterPrivateClusterConfig `pulumi:"privateClusterConfig"`
	Project              *string                                             `pulumi:"project"`
	// Name of the Compute Engine subnetwork in which instances associated with this cluster will be created. Must be part of
	// the subnetwork specified for this cluster.
	Subnetwork string                                  `pulumi:"subnetwork"`
	Timeouts   *WorkstationsWorkstationClusterTimeouts `pulumi:"timeouts"`
	// ID to use for the workstation cluster.
	WorkstationClusterId             string  `pulumi:"workstationClusterId"`
	WorkstationsWorkstationClusterId *string `pulumi:"workstationsWorkstationClusterId"`
}

// The set of arguments for constructing a WorkstationsWorkstationCluster resource.
type WorkstationsWorkstationClusterArgs struct {
	// Client-specified annotations. This is distinct from labels. **Note**: This field is non-authoritative, and will only
	// manage the annotations present in your configuration. Please refer to the field 'effective_annotations' for all of the
	// annotations present on the resource.
	Annotations pulumi.StringMapInput
	// Human-readable name for this resource.
	DisplayName pulumi.StringPtrInput
	// Configuration options for a custom domain.
	DomainConfig WorkstationsWorkstationClusterDomainConfigPtrInput
	// Client-specified labels that are applied to the resource and that are also propagated to the underlying Compute Engine
	// resources. **Note**: This field is non-authoritative, and will only manage the labels present in your configuration.
	// Please refer to the field 'effective_labels' for all of the labels present on the resource.
	Labels pulumi.StringMapInput
	// The location where the workstation cluster should reside.
	Location pulumi.StringPtrInput
	// The relative resource name of the VPC network on which the instance can be accessed. It is specified in the following
	// form: "projects/{projectNumber}/global/networks/{network_id}".
	Network pulumi.StringInput
	// Configuration for private cluster.
	PrivateClusterConfig WorkstationsWorkstationClusterPrivateClusterConfigPtrInput
	Project              pulumi.StringPtrInput
	// Name of the Compute Engine subnetwork in which instances associated with this cluster will be created. Must be part of
	// the subnetwork specified for this cluster.
	Subnetwork pulumi.StringInput
	Timeouts   WorkstationsWorkstationClusterTimeoutsPtrInput
	// ID to use for the workstation cluster.
	WorkstationClusterId             pulumi.StringInput
	WorkstationsWorkstationClusterId pulumi.StringPtrInput
}

func (WorkstationsWorkstationClusterArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*workstationsWorkstationClusterArgs)(nil)).Elem()
}

type WorkstationsWorkstationClusterInput interface {
	pulumi.Input

	ToWorkstationsWorkstationClusterOutput() WorkstationsWorkstationClusterOutput
	ToWorkstationsWorkstationClusterOutputWithContext(ctx context.Context) WorkstationsWorkstationClusterOutput
}

func (*WorkstationsWorkstationCluster) ElementType() reflect.Type {
	return reflect.TypeOf((**WorkstationsWorkstationCluster)(nil)).Elem()
}

func (i *WorkstationsWorkstationCluster) ToWorkstationsWorkstationClusterOutput() WorkstationsWorkstationClusterOutput {
	return i.ToWorkstationsWorkstationClusterOutputWithContext(context.Background())
}

func (i *WorkstationsWorkstationCluster) ToWorkstationsWorkstationClusterOutputWithContext(ctx context.Context) WorkstationsWorkstationClusterOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkstationsWorkstationClusterOutput)
}

type WorkstationsWorkstationClusterOutput struct{ *pulumi.OutputState }

func (WorkstationsWorkstationClusterOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**WorkstationsWorkstationCluster)(nil)).Elem()
}

func (o WorkstationsWorkstationClusterOutput) ToWorkstationsWorkstationClusterOutput() WorkstationsWorkstationClusterOutput {
	return o
}

func (o WorkstationsWorkstationClusterOutput) ToWorkstationsWorkstationClusterOutputWithContext(ctx context.Context) WorkstationsWorkstationClusterOutput {
	return o
}

// Client-specified annotations. This is distinct from labels. **Note**: This field is non-authoritative, and will only
// manage the annotations present in your configuration. Please refer to the field 'effective_annotations' for all of the
// annotations present on the resource.
func (o WorkstationsWorkstationClusterOutput) Annotations() pulumi.StringMapOutput {
	return o.ApplyT(func(v *WorkstationsWorkstationCluster) pulumi.StringMapOutput { return v.Annotations }).(pulumi.StringMapOutput)
}

// Status conditions describing the current resource state.
func (o WorkstationsWorkstationClusterOutput) Conditions() WorkstationsWorkstationClusterConditionArrayOutput {
	return o.ApplyT(func(v *WorkstationsWorkstationCluster) WorkstationsWorkstationClusterConditionArrayOutput {
		return v.Conditions
	}).(WorkstationsWorkstationClusterConditionArrayOutput)
}

// The private IP address of the control plane for this workstation cluster. Workstation VMs need access to this IP address
// to work with the service, so make sure that your firewall rules allow egress from the workstation VMs to this address.
func (o WorkstationsWorkstationClusterOutput) ControlPlaneIp() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkstationsWorkstationCluster) pulumi.StringOutput { return v.ControlPlaneIp }).(pulumi.StringOutput)
}

// Time when this resource was created.
func (o WorkstationsWorkstationClusterOutput) CreateTime() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkstationsWorkstationCluster) pulumi.StringOutput { return v.CreateTime }).(pulumi.StringOutput)
}

// Whether this resource is in degraded mode, in which case it may require user action to restore full functionality.
// Details can be found in the conditions field.
func (o WorkstationsWorkstationClusterOutput) Degraded() pulumi.BoolOutput {
	return o.ApplyT(func(v *WorkstationsWorkstationCluster) pulumi.BoolOutput { return v.Degraded }).(pulumi.BoolOutput)
}

// Human-readable name for this resource.
func (o WorkstationsWorkstationClusterOutput) DisplayName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WorkstationsWorkstationCluster) pulumi.StringPtrOutput { return v.DisplayName }).(pulumi.StringPtrOutput)
}

// Configuration options for a custom domain.
func (o WorkstationsWorkstationClusterOutput) DomainConfig() WorkstationsWorkstationClusterDomainConfigPtrOutput {
	return o.ApplyT(func(v *WorkstationsWorkstationCluster) WorkstationsWorkstationClusterDomainConfigPtrOutput {
		return v.DomainConfig
	}).(WorkstationsWorkstationClusterDomainConfigPtrOutput)
}

func (o WorkstationsWorkstationClusterOutput) EffectiveAnnotations() pulumi.StringMapOutput {
	return o.ApplyT(func(v *WorkstationsWorkstationCluster) pulumi.StringMapOutput { return v.EffectiveAnnotations }).(pulumi.StringMapOutput)
}

func (o WorkstationsWorkstationClusterOutput) EffectiveLabels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *WorkstationsWorkstationCluster) pulumi.StringMapOutput { return v.EffectiveLabels }).(pulumi.StringMapOutput)
}

// Checksum computed by the server. May be sent on update and delete requests to ensure that the client has an up-to-date
// value before proceeding.
func (o WorkstationsWorkstationClusterOutput) Etag() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkstationsWorkstationCluster) pulumi.StringOutput { return v.Etag }).(pulumi.StringOutput)
}

// Client-specified labels that are applied to the resource and that are also propagated to the underlying Compute Engine
// resources. **Note**: This field is non-authoritative, and will only manage the labels present in your configuration.
// Please refer to the field 'effective_labels' for all of the labels present on the resource.
func (o WorkstationsWorkstationClusterOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *WorkstationsWorkstationCluster) pulumi.StringMapOutput { return v.Labels }).(pulumi.StringMapOutput)
}

// The location where the workstation cluster should reside.
func (o WorkstationsWorkstationClusterOutput) Location() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WorkstationsWorkstationCluster) pulumi.StringPtrOutput { return v.Location }).(pulumi.StringPtrOutput)
}

// The name of the cluster resource.
func (o WorkstationsWorkstationClusterOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkstationsWorkstationCluster) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The relative resource name of the VPC network on which the instance can be accessed. It is specified in the following
// form: "projects/{projectNumber}/global/networks/{network_id}".
func (o WorkstationsWorkstationClusterOutput) Network() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkstationsWorkstationCluster) pulumi.StringOutput { return v.Network }).(pulumi.StringOutput)
}

// Configuration for private cluster.
func (o WorkstationsWorkstationClusterOutput) PrivateClusterConfig() WorkstationsWorkstationClusterPrivateClusterConfigPtrOutput {
	return o.ApplyT(func(v *WorkstationsWorkstationCluster) WorkstationsWorkstationClusterPrivateClusterConfigPtrOutput {
		return v.PrivateClusterConfig
	}).(WorkstationsWorkstationClusterPrivateClusterConfigPtrOutput)
}

func (o WorkstationsWorkstationClusterOutput) Project() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkstationsWorkstationCluster) pulumi.StringOutput { return v.Project }).(pulumi.StringOutput)
}

// Name of the Compute Engine subnetwork in which instances associated with this cluster will be created. Must be part of
// the subnetwork specified for this cluster.
func (o WorkstationsWorkstationClusterOutput) Subnetwork() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkstationsWorkstationCluster) pulumi.StringOutput { return v.Subnetwork }).(pulumi.StringOutput)
}

// The combination of labels configured directly on the resource and default labels configured on the provider.
func (o WorkstationsWorkstationClusterOutput) TerraformLabels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *WorkstationsWorkstationCluster) pulumi.StringMapOutput { return v.TerraformLabels }).(pulumi.StringMapOutput)
}

func (o WorkstationsWorkstationClusterOutput) Timeouts() WorkstationsWorkstationClusterTimeoutsPtrOutput {
	return o.ApplyT(func(v *WorkstationsWorkstationCluster) WorkstationsWorkstationClusterTimeoutsPtrOutput {
		return v.Timeouts
	}).(WorkstationsWorkstationClusterTimeoutsPtrOutput)
}

// The system-generated UID of the resource.
func (o WorkstationsWorkstationClusterOutput) Uid() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkstationsWorkstationCluster) pulumi.StringOutput { return v.Uid }).(pulumi.StringOutput)
}

// ID to use for the workstation cluster.
func (o WorkstationsWorkstationClusterOutput) WorkstationClusterId() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkstationsWorkstationCluster) pulumi.StringOutput { return v.WorkstationClusterId }).(pulumi.StringOutput)
}

func (o WorkstationsWorkstationClusterOutput) WorkstationsWorkstationClusterId() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkstationsWorkstationCluster) pulumi.StringOutput { return v.WorkstationsWorkstationClusterId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*WorkstationsWorkstationClusterInput)(nil)).Elem(), &WorkstationsWorkstationCluster{})
	pulumi.RegisterOutputType(WorkstationsWorkstationClusterOutput{})
}
