// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package google

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/google/v6/google/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type BigqueryJob struct {
	pulumi.CustomResourceState

	BigqueryJobId pulumi.StringOutput `pulumi:"bigqueryJobId"`
	// Copies a table.
	Copy            BigqueryJobCopyPtrOutput `pulumi:"copy"`
	EffectiveLabels pulumi.StringMapOutput   `pulumi:"effectiveLabels"`
	// Configures an extract job.
	Extract BigqueryJobExtractPtrOutput `pulumi:"extract"`
	// The ID of the job. The ID must contain only letters (a-z, A-Z), numbers (0-9), underscores (_), or dashes (-). The
	// maximum length is 1,024 characters.
	JobId pulumi.StringOutput `pulumi:"jobId"`
	// Job timeout in milliseconds. If this time limit is exceeded, BigQuery may attempt to terminate the job.
	JobTimeoutMs pulumi.StringPtrOutput `pulumi:"jobTimeoutMs"`
	// The type of the job.
	JobType pulumi.StringOutput `pulumi:"jobType"`
	// The labels associated with this job. You can use these to organize and group your jobs. **Note**: This field is
	// non-authoritative, and will only manage the labels present in your configuration. Please refer to the field
	// 'effective_labels' for all of the labels present on the resource.
	Labels pulumi.StringMapOutput `pulumi:"labels"`
	// Configures a load job.
	Load BigqueryJobLoadPtrOutput `pulumi:"load"`
	// The geographic location of the job. The default value is US.
	Location pulumi.StringPtrOutput `pulumi:"location"`
	Project  pulumi.StringOutput    `pulumi:"project"`
	// Configures a query job.
	Query BigqueryJobQueryPtrOutput `pulumi:"query"`
	// The status of this job. Examine this value when polling an asynchronous job to see if the job is complete.
	Statuses BigqueryJobStatusArrayOutput `pulumi:"statuses"`
	// The combination of labels configured directly on the resource and default labels configured on the provider.
	TerraformLabels pulumi.StringMapOutput       `pulumi:"terraformLabels"`
	Timeouts        BigqueryJobTimeoutsPtrOutput `pulumi:"timeouts"`
	// Email address of the user who ran the job.
	UserEmail pulumi.StringOutput `pulumi:"userEmail"`
}

// NewBigqueryJob registers a new resource with the given unique name, arguments, and options.
func NewBigqueryJob(ctx *pulumi.Context,
	name string, args *BigqueryJobArgs, opts ...pulumi.ResourceOption) (*BigqueryJob, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.JobId == nil {
		return nil, errors.New("invalid value for required argument 'JobId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource BigqueryJob
	err = ctx.RegisterPackageResource("google:index/bigqueryJob:BigqueryJob", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetBigqueryJob gets an existing BigqueryJob resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetBigqueryJob(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *BigqueryJobState, opts ...pulumi.ResourceOption) (*BigqueryJob, error) {
	var resource BigqueryJob
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("google:index/bigqueryJob:BigqueryJob", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering BigqueryJob resources.
type bigqueryJobState struct {
	BigqueryJobId *string `pulumi:"bigqueryJobId"`
	// Copies a table.
	Copy            *BigqueryJobCopy  `pulumi:"copy"`
	EffectiveLabels map[string]string `pulumi:"effectiveLabels"`
	// Configures an extract job.
	Extract *BigqueryJobExtract `pulumi:"extract"`
	// The ID of the job. The ID must contain only letters (a-z, A-Z), numbers (0-9), underscores (_), or dashes (-). The
	// maximum length is 1,024 characters.
	JobId *string `pulumi:"jobId"`
	// Job timeout in milliseconds. If this time limit is exceeded, BigQuery may attempt to terminate the job.
	JobTimeoutMs *string `pulumi:"jobTimeoutMs"`
	// The type of the job.
	JobType *string `pulumi:"jobType"`
	// The labels associated with this job. You can use these to organize and group your jobs. **Note**: This field is
	// non-authoritative, and will only manage the labels present in your configuration. Please refer to the field
	// 'effective_labels' for all of the labels present on the resource.
	Labels map[string]string `pulumi:"labels"`
	// Configures a load job.
	Load *BigqueryJobLoad `pulumi:"load"`
	// The geographic location of the job. The default value is US.
	Location *string `pulumi:"location"`
	Project  *string `pulumi:"project"`
	// Configures a query job.
	Query *BigqueryJobQuery `pulumi:"query"`
	// The status of this job. Examine this value when polling an asynchronous job to see if the job is complete.
	Statuses []BigqueryJobStatus `pulumi:"statuses"`
	// The combination of labels configured directly on the resource and default labels configured on the provider.
	TerraformLabels map[string]string    `pulumi:"terraformLabels"`
	Timeouts        *BigqueryJobTimeouts `pulumi:"timeouts"`
	// Email address of the user who ran the job.
	UserEmail *string `pulumi:"userEmail"`
}

type BigqueryJobState struct {
	BigqueryJobId pulumi.StringPtrInput
	// Copies a table.
	Copy            BigqueryJobCopyPtrInput
	EffectiveLabels pulumi.StringMapInput
	// Configures an extract job.
	Extract BigqueryJobExtractPtrInput
	// The ID of the job. The ID must contain only letters (a-z, A-Z), numbers (0-9), underscores (_), or dashes (-). The
	// maximum length is 1,024 characters.
	JobId pulumi.StringPtrInput
	// Job timeout in milliseconds. If this time limit is exceeded, BigQuery may attempt to terminate the job.
	JobTimeoutMs pulumi.StringPtrInput
	// The type of the job.
	JobType pulumi.StringPtrInput
	// The labels associated with this job. You can use these to organize and group your jobs. **Note**: This field is
	// non-authoritative, and will only manage the labels present in your configuration. Please refer to the field
	// 'effective_labels' for all of the labels present on the resource.
	Labels pulumi.StringMapInput
	// Configures a load job.
	Load BigqueryJobLoadPtrInput
	// The geographic location of the job. The default value is US.
	Location pulumi.StringPtrInput
	Project  pulumi.StringPtrInput
	// Configures a query job.
	Query BigqueryJobQueryPtrInput
	// The status of this job. Examine this value when polling an asynchronous job to see if the job is complete.
	Statuses BigqueryJobStatusArrayInput
	// The combination of labels configured directly on the resource and default labels configured on the provider.
	TerraformLabels pulumi.StringMapInput
	Timeouts        BigqueryJobTimeoutsPtrInput
	// Email address of the user who ran the job.
	UserEmail pulumi.StringPtrInput
}

func (BigqueryJobState) ElementType() reflect.Type {
	return reflect.TypeOf((*bigqueryJobState)(nil)).Elem()
}

type bigqueryJobArgs struct {
	BigqueryJobId *string `pulumi:"bigqueryJobId"`
	// Copies a table.
	Copy *BigqueryJobCopy `pulumi:"copy"`
	// Configures an extract job.
	Extract *BigqueryJobExtract `pulumi:"extract"`
	// The ID of the job. The ID must contain only letters (a-z, A-Z), numbers (0-9), underscores (_), or dashes (-). The
	// maximum length is 1,024 characters.
	JobId string `pulumi:"jobId"`
	// Job timeout in milliseconds. If this time limit is exceeded, BigQuery may attempt to terminate the job.
	JobTimeoutMs *string `pulumi:"jobTimeoutMs"`
	// The labels associated with this job. You can use these to organize and group your jobs. **Note**: This field is
	// non-authoritative, and will only manage the labels present in your configuration. Please refer to the field
	// 'effective_labels' for all of the labels present on the resource.
	Labels map[string]string `pulumi:"labels"`
	// Configures a load job.
	Load *BigqueryJobLoad `pulumi:"load"`
	// The geographic location of the job. The default value is US.
	Location *string `pulumi:"location"`
	Project  *string `pulumi:"project"`
	// Configures a query job.
	Query    *BigqueryJobQuery    `pulumi:"query"`
	Timeouts *BigqueryJobTimeouts `pulumi:"timeouts"`
}

// The set of arguments for constructing a BigqueryJob resource.
type BigqueryJobArgs struct {
	BigqueryJobId pulumi.StringPtrInput
	// Copies a table.
	Copy BigqueryJobCopyPtrInput
	// Configures an extract job.
	Extract BigqueryJobExtractPtrInput
	// The ID of the job. The ID must contain only letters (a-z, A-Z), numbers (0-9), underscores (_), or dashes (-). The
	// maximum length is 1,024 characters.
	JobId pulumi.StringInput
	// Job timeout in milliseconds. If this time limit is exceeded, BigQuery may attempt to terminate the job.
	JobTimeoutMs pulumi.StringPtrInput
	// The labels associated with this job. You can use these to organize and group your jobs. **Note**: This field is
	// non-authoritative, and will only manage the labels present in your configuration. Please refer to the field
	// 'effective_labels' for all of the labels present on the resource.
	Labels pulumi.StringMapInput
	// Configures a load job.
	Load BigqueryJobLoadPtrInput
	// The geographic location of the job. The default value is US.
	Location pulumi.StringPtrInput
	Project  pulumi.StringPtrInput
	// Configures a query job.
	Query    BigqueryJobQueryPtrInput
	Timeouts BigqueryJobTimeoutsPtrInput
}

func (BigqueryJobArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*bigqueryJobArgs)(nil)).Elem()
}

type BigqueryJobInput interface {
	pulumi.Input

	ToBigqueryJobOutput() BigqueryJobOutput
	ToBigqueryJobOutputWithContext(ctx context.Context) BigqueryJobOutput
}

func (*BigqueryJob) ElementType() reflect.Type {
	return reflect.TypeOf((**BigqueryJob)(nil)).Elem()
}

func (i *BigqueryJob) ToBigqueryJobOutput() BigqueryJobOutput {
	return i.ToBigqueryJobOutputWithContext(context.Background())
}

func (i *BigqueryJob) ToBigqueryJobOutputWithContext(ctx context.Context) BigqueryJobOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BigqueryJobOutput)
}

type BigqueryJobOutput struct{ *pulumi.OutputState }

func (BigqueryJobOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**BigqueryJob)(nil)).Elem()
}

func (o BigqueryJobOutput) ToBigqueryJobOutput() BigqueryJobOutput {
	return o
}

func (o BigqueryJobOutput) ToBigqueryJobOutputWithContext(ctx context.Context) BigqueryJobOutput {
	return o
}

func (o BigqueryJobOutput) BigqueryJobId() pulumi.StringOutput {
	return o.ApplyT(func(v *BigqueryJob) pulumi.StringOutput { return v.BigqueryJobId }).(pulumi.StringOutput)
}

// Copies a table.
func (o BigqueryJobOutput) Copy() BigqueryJobCopyPtrOutput {
	return o.ApplyT(func(v *BigqueryJob) BigqueryJobCopyPtrOutput { return v.Copy }).(BigqueryJobCopyPtrOutput)
}

func (o BigqueryJobOutput) EffectiveLabels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *BigqueryJob) pulumi.StringMapOutput { return v.EffectiveLabels }).(pulumi.StringMapOutput)
}

// Configures an extract job.
func (o BigqueryJobOutput) Extract() BigqueryJobExtractPtrOutput {
	return o.ApplyT(func(v *BigqueryJob) BigqueryJobExtractPtrOutput { return v.Extract }).(BigqueryJobExtractPtrOutput)
}

// The ID of the job. The ID must contain only letters (a-z, A-Z), numbers (0-9), underscores (_), or dashes (-). The
// maximum length is 1,024 characters.
func (o BigqueryJobOutput) JobId() pulumi.StringOutput {
	return o.ApplyT(func(v *BigqueryJob) pulumi.StringOutput { return v.JobId }).(pulumi.StringOutput)
}

// Job timeout in milliseconds. If this time limit is exceeded, BigQuery may attempt to terminate the job.
func (o BigqueryJobOutput) JobTimeoutMs() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *BigqueryJob) pulumi.StringPtrOutput { return v.JobTimeoutMs }).(pulumi.StringPtrOutput)
}

// The type of the job.
func (o BigqueryJobOutput) JobType() pulumi.StringOutput {
	return o.ApplyT(func(v *BigqueryJob) pulumi.StringOutput { return v.JobType }).(pulumi.StringOutput)
}

// The labels associated with this job. You can use these to organize and group your jobs. **Note**: This field is
// non-authoritative, and will only manage the labels present in your configuration. Please refer to the field
// 'effective_labels' for all of the labels present on the resource.
func (o BigqueryJobOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *BigqueryJob) pulumi.StringMapOutput { return v.Labels }).(pulumi.StringMapOutput)
}

// Configures a load job.
func (o BigqueryJobOutput) Load() BigqueryJobLoadPtrOutput {
	return o.ApplyT(func(v *BigqueryJob) BigqueryJobLoadPtrOutput { return v.Load }).(BigqueryJobLoadPtrOutput)
}

// The geographic location of the job. The default value is US.
func (o BigqueryJobOutput) Location() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *BigqueryJob) pulumi.StringPtrOutput { return v.Location }).(pulumi.StringPtrOutput)
}

func (o BigqueryJobOutput) Project() pulumi.StringOutput {
	return o.ApplyT(func(v *BigqueryJob) pulumi.StringOutput { return v.Project }).(pulumi.StringOutput)
}

// Configures a query job.
func (o BigqueryJobOutput) Query() BigqueryJobQueryPtrOutput {
	return o.ApplyT(func(v *BigqueryJob) BigqueryJobQueryPtrOutput { return v.Query }).(BigqueryJobQueryPtrOutput)
}

// The status of this job. Examine this value when polling an asynchronous job to see if the job is complete.
func (o BigqueryJobOutput) Statuses() BigqueryJobStatusArrayOutput {
	return o.ApplyT(func(v *BigqueryJob) BigqueryJobStatusArrayOutput { return v.Statuses }).(BigqueryJobStatusArrayOutput)
}

// The combination of labels configured directly on the resource and default labels configured on the provider.
func (o BigqueryJobOutput) TerraformLabels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *BigqueryJob) pulumi.StringMapOutput { return v.TerraformLabels }).(pulumi.StringMapOutput)
}

func (o BigqueryJobOutput) Timeouts() BigqueryJobTimeoutsPtrOutput {
	return o.ApplyT(func(v *BigqueryJob) BigqueryJobTimeoutsPtrOutput { return v.Timeouts }).(BigqueryJobTimeoutsPtrOutput)
}

// Email address of the user who ran the job.
func (o BigqueryJobOutput) UserEmail() pulumi.StringOutput {
	return o.ApplyT(func(v *BigqueryJob) pulumi.StringOutput { return v.UserEmail }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*BigqueryJobInput)(nil)).Elem(), &BigqueryJob{})
	pulumi.RegisterOutputType(BigqueryJobOutput{})
}
