// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package google

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/google/v6/google/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ComputeRegionTargetHttpsProxy struct {
	pulumi.CustomResourceState

	// URLs to certificate manager certificate resources that are used to authenticate connections between users and the load
	// balancer. sslCertificates and certificateManagerCertificates can't be defined together. Accepted format is
	// '//certificatemanager.googleapis.com/projects/{project}/locations/{location}/certificates/{resourceName}' or just the
	// self_link 'projects/{project}/locations/{location}/certificates/{resourceName}'
	CertificateManagerCertificates  pulumi.StringArrayOutput `pulumi:"certificateManagerCertificates"`
	ComputeRegionTargetHttpsProxyId pulumi.StringOutput      `pulumi:"computeRegionTargetHttpsProxyId"`
	// Creation timestamp in RFC3339 text format.
	CreationTimestamp pulumi.StringOutput `pulumi:"creationTimestamp"`
	// An optional description of this resource.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Specifies how long to keep a connection open, after completing a response, while there is no matching traffic (in
	// seconds). If an HTTP keepalive is not specified, a default value (600 seconds) will be used. For Regioanl HTTP(S) load
	// balancer, the minimum allowed value is 5 seconds and the maximum allowed value is 600 seconds.
	HttpKeepAliveTimeoutSec pulumi.Float64PtrOutput `pulumi:"httpKeepAliveTimeoutSec"`
	// Name of the resource. Provided by the client when the resource is created. The name must be 1-63 characters long, and
	// comply with RFC1035. Specifically, the name must be 1-63 characters long and match the regular expression 'a-z?' which
	// means the first character must be a lowercase letter, and all following characters must be a dash, lowercase letter, or
	// digit, except the last character, which cannot be a dash.
	Name    pulumi.StringOutput `pulumi:"name"`
	Project pulumi.StringOutput `pulumi:"project"`
	// The unique identifier for the resource.
	ProxyId pulumi.Float64Output `pulumi:"proxyId"`
	// The Region in which the created target https proxy should reside. If it is not provided, the provider region is used.
	Region   pulumi.StringOutput `pulumi:"region"`
	SelfLink pulumi.StringOutput `pulumi:"selfLink"`
	// A URL referring to a networksecurity.ServerTlsPolicy resource that describes how the proxy should authenticate inbound
	// traffic. serverTlsPolicy only applies to a global TargetHttpsProxy attached to globalForwardingRules with the
	// loadBalancingScheme set to INTERNAL_SELF_MANAGED or EXTERNAL or EXTERNAL_MANAGED. For details which ServerTlsPolicy
	// resources are accepted with INTERNAL_SELF_MANAGED and which with EXTERNAL, EXTERNAL_MANAGED loadBalancingScheme consult
	// ServerTlsPolicy documentation. If left blank, communications are not encrypted. If you remove this field from your
	// configuration at the same time as deleting or recreating a referenced ServerTlsPolicy resource, you will receive a
	// resourceInUseByAnotherResource error. Use lifecycle.create_before_destroy within the ServerTlsPolicy resource to avoid
	// this.
	ServerTlsPolicy pulumi.StringPtrOutput `pulumi:"serverTlsPolicy"`
	// URLs to SslCertificate resources that are used to authenticate connections between users and the load balancer. At least
	// one SSL certificate must be specified. Currently, you may specify up to 15 SSL certificates. sslCertificates do not
	// apply when the load balancing scheme is set to INTERNAL_SELF_MANAGED.
	SslCertificates pulumi.StringArrayOutput `pulumi:"sslCertificates"`
	// A reference to the Region SslPolicy resource that will be associated with the TargetHttpsProxy resource. If not set, the
	// TargetHttpsProxy resource will not have any SSL policy configured.
	SslPolicy pulumi.StringPtrOutput                         `pulumi:"sslPolicy"`
	Timeouts  ComputeRegionTargetHttpsProxyTimeoutsPtrOutput `pulumi:"timeouts"`
	// A reference to the RegionUrlMap resource that defines the mapping from URL to the RegionBackendService.
	UrlMap pulumi.StringOutput `pulumi:"urlMap"`
}

// NewComputeRegionTargetHttpsProxy registers a new resource with the given unique name, arguments, and options.
func NewComputeRegionTargetHttpsProxy(ctx *pulumi.Context,
	name string, args *ComputeRegionTargetHttpsProxyArgs, opts ...pulumi.ResourceOption) (*ComputeRegionTargetHttpsProxy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.UrlMap == nil {
		return nil, errors.New("invalid value for required argument 'UrlMap'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource ComputeRegionTargetHttpsProxy
	err = ctx.RegisterPackageResource("google:index/computeRegionTargetHttpsProxy:ComputeRegionTargetHttpsProxy", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetComputeRegionTargetHttpsProxy gets an existing ComputeRegionTargetHttpsProxy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetComputeRegionTargetHttpsProxy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ComputeRegionTargetHttpsProxyState, opts ...pulumi.ResourceOption) (*ComputeRegionTargetHttpsProxy, error) {
	var resource ComputeRegionTargetHttpsProxy
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("google:index/computeRegionTargetHttpsProxy:ComputeRegionTargetHttpsProxy", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ComputeRegionTargetHttpsProxy resources.
type computeRegionTargetHttpsProxyState struct {
	// URLs to certificate manager certificate resources that are used to authenticate connections between users and the load
	// balancer. sslCertificates and certificateManagerCertificates can't be defined together. Accepted format is
	// '//certificatemanager.googleapis.com/projects/{project}/locations/{location}/certificates/{resourceName}' or just the
	// self_link 'projects/{project}/locations/{location}/certificates/{resourceName}'
	CertificateManagerCertificates  []string `pulumi:"certificateManagerCertificates"`
	ComputeRegionTargetHttpsProxyId *string  `pulumi:"computeRegionTargetHttpsProxyId"`
	// Creation timestamp in RFC3339 text format.
	CreationTimestamp *string `pulumi:"creationTimestamp"`
	// An optional description of this resource.
	Description *string `pulumi:"description"`
	// Specifies how long to keep a connection open, after completing a response, while there is no matching traffic (in
	// seconds). If an HTTP keepalive is not specified, a default value (600 seconds) will be used. For Regioanl HTTP(S) load
	// balancer, the minimum allowed value is 5 seconds and the maximum allowed value is 600 seconds.
	HttpKeepAliveTimeoutSec *float64 `pulumi:"httpKeepAliveTimeoutSec"`
	// Name of the resource. Provided by the client when the resource is created. The name must be 1-63 characters long, and
	// comply with RFC1035. Specifically, the name must be 1-63 characters long and match the regular expression 'a-z?' which
	// means the first character must be a lowercase letter, and all following characters must be a dash, lowercase letter, or
	// digit, except the last character, which cannot be a dash.
	Name    *string `pulumi:"name"`
	Project *string `pulumi:"project"`
	// The unique identifier for the resource.
	ProxyId *float64 `pulumi:"proxyId"`
	// The Region in which the created target https proxy should reside. If it is not provided, the provider region is used.
	Region   *string `pulumi:"region"`
	SelfLink *string `pulumi:"selfLink"`
	// A URL referring to a networksecurity.ServerTlsPolicy resource that describes how the proxy should authenticate inbound
	// traffic. serverTlsPolicy only applies to a global TargetHttpsProxy attached to globalForwardingRules with the
	// loadBalancingScheme set to INTERNAL_SELF_MANAGED or EXTERNAL or EXTERNAL_MANAGED. For details which ServerTlsPolicy
	// resources are accepted with INTERNAL_SELF_MANAGED and which with EXTERNAL, EXTERNAL_MANAGED loadBalancingScheme consult
	// ServerTlsPolicy documentation. If left blank, communications are not encrypted. If you remove this field from your
	// configuration at the same time as deleting or recreating a referenced ServerTlsPolicy resource, you will receive a
	// resourceInUseByAnotherResource error. Use lifecycle.create_before_destroy within the ServerTlsPolicy resource to avoid
	// this.
	ServerTlsPolicy *string `pulumi:"serverTlsPolicy"`
	// URLs to SslCertificate resources that are used to authenticate connections between users and the load balancer. At least
	// one SSL certificate must be specified. Currently, you may specify up to 15 SSL certificates. sslCertificates do not
	// apply when the load balancing scheme is set to INTERNAL_SELF_MANAGED.
	SslCertificates []string `pulumi:"sslCertificates"`
	// A reference to the Region SslPolicy resource that will be associated with the TargetHttpsProxy resource. If not set, the
	// TargetHttpsProxy resource will not have any SSL policy configured.
	SslPolicy *string                                `pulumi:"sslPolicy"`
	Timeouts  *ComputeRegionTargetHttpsProxyTimeouts `pulumi:"timeouts"`
	// A reference to the RegionUrlMap resource that defines the mapping from URL to the RegionBackendService.
	UrlMap *string `pulumi:"urlMap"`
}

type ComputeRegionTargetHttpsProxyState struct {
	// URLs to certificate manager certificate resources that are used to authenticate connections between users and the load
	// balancer. sslCertificates and certificateManagerCertificates can't be defined together. Accepted format is
	// '//certificatemanager.googleapis.com/projects/{project}/locations/{location}/certificates/{resourceName}' or just the
	// self_link 'projects/{project}/locations/{location}/certificates/{resourceName}'
	CertificateManagerCertificates  pulumi.StringArrayInput
	ComputeRegionTargetHttpsProxyId pulumi.StringPtrInput
	// Creation timestamp in RFC3339 text format.
	CreationTimestamp pulumi.StringPtrInput
	// An optional description of this resource.
	Description pulumi.StringPtrInput
	// Specifies how long to keep a connection open, after completing a response, while there is no matching traffic (in
	// seconds). If an HTTP keepalive is not specified, a default value (600 seconds) will be used. For Regioanl HTTP(S) load
	// balancer, the minimum allowed value is 5 seconds and the maximum allowed value is 600 seconds.
	HttpKeepAliveTimeoutSec pulumi.Float64PtrInput
	// Name of the resource. Provided by the client when the resource is created. The name must be 1-63 characters long, and
	// comply with RFC1035. Specifically, the name must be 1-63 characters long and match the regular expression 'a-z?' which
	// means the first character must be a lowercase letter, and all following characters must be a dash, lowercase letter, or
	// digit, except the last character, which cannot be a dash.
	Name    pulumi.StringPtrInput
	Project pulumi.StringPtrInput
	// The unique identifier for the resource.
	ProxyId pulumi.Float64PtrInput
	// The Region in which the created target https proxy should reside. If it is not provided, the provider region is used.
	Region   pulumi.StringPtrInput
	SelfLink pulumi.StringPtrInput
	// A URL referring to a networksecurity.ServerTlsPolicy resource that describes how the proxy should authenticate inbound
	// traffic. serverTlsPolicy only applies to a global TargetHttpsProxy attached to globalForwardingRules with the
	// loadBalancingScheme set to INTERNAL_SELF_MANAGED or EXTERNAL or EXTERNAL_MANAGED. For details which ServerTlsPolicy
	// resources are accepted with INTERNAL_SELF_MANAGED and which with EXTERNAL, EXTERNAL_MANAGED loadBalancingScheme consult
	// ServerTlsPolicy documentation. If left blank, communications are not encrypted. If you remove this field from your
	// configuration at the same time as deleting or recreating a referenced ServerTlsPolicy resource, you will receive a
	// resourceInUseByAnotherResource error. Use lifecycle.create_before_destroy within the ServerTlsPolicy resource to avoid
	// this.
	ServerTlsPolicy pulumi.StringPtrInput
	// URLs to SslCertificate resources that are used to authenticate connections between users and the load balancer. At least
	// one SSL certificate must be specified. Currently, you may specify up to 15 SSL certificates. sslCertificates do not
	// apply when the load balancing scheme is set to INTERNAL_SELF_MANAGED.
	SslCertificates pulumi.StringArrayInput
	// A reference to the Region SslPolicy resource that will be associated with the TargetHttpsProxy resource. If not set, the
	// TargetHttpsProxy resource will not have any SSL policy configured.
	SslPolicy pulumi.StringPtrInput
	Timeouts  ComputeRegionTargetHttpsProxyTimeoutsPtrInput
	// A reference to the RegionUrlMap resource that defines the mapping from URL to the RegionBackendService.
	UrlMap pulumi.StringPtrInput
}

func (ComputeRegionTargetHttpsProxyState) ElementType() reflect.Type {
	return reflect.TypeOf((*computeRegionTargetHttpsProxyState)(nil)).Elem()
}

type computeRegionTargetHttpsProxyArgs struct {
	// URLs to certificate manager certificate resources that are used to authenticate connections between users and the load
	// balancer. sslCertificates and certificateManagerCertificates can't be defined together. Accepted format is
	// '//certificatemanager.googleapis.com/projects/{project}/locations/{location}/certificates/{resourceName}' or just the
	// self_link 'projects/{project}/locations/{location}/certificates/{resourceName}'
	CertificateManagerCertificates  []string `pulumi:"certificateManagerCertificates"`
	ComputeRegionTargetHttpsProxyId *string  `pulumi:"computeRegionTargetHttpsProxyId"`
	// An optional description of this resource.
	Description *string `pulumi:"description"`
	// Specifies how long to keep a connection open, after completing a response, while there is no matching traffic (in
	// seconds). If an HTTP keepalive is not specified, a default value (600 seconds) will be used. For Regioanl HTTP(S) load
	// balancer, the minimum allowed value is 5 seconds and the maximum allowed value is 600 seconds.
	HttpKeepAliveTimeoutSec *float64 `pulumi:"httpKeepAliveTimeoutSec"`
	// Name of the resource. Provided by the client when the resource is created. The name must be 1-63 characters long, and
	// comply with RFC1035. Specifically, the name must be 1-63 characters long and match the regular expression 'a-z?' which
	// means the first character must be a lowercase letter, and all following characters must be a dash, lowercase letter, or
	// digit, except the last character, which cannot be a dash.
	Name    *string `pulumi:"name"`
	Project *string `pulumi:"project"`
	// The Region in which the created target https proxy should reside. If it is not provided, the provider region is used.
	Region *string `pulumi:"region"`
	// A URL referring to a networksecurity.ServerTlsPolicy resource that describes how the proxy should authenticate inbound
	// traffic. serverTlsPolicy only applies to a global TargetHttpsProxy attached to globalForwardingRules with the
	// loadBalancingScheme set to INTERNAL_SELF_MANAGED or EXTERNAL or EXTERNAL_MANAGED. For details which ServerTlsPolicy
	// resources are accepted with INTERNAL_SELF_MANAGED and which with EXTERNAL, EXTERNAL_MANAGED loadBalancingScheme consult
	// ServerTlsPolicy documentation. If left blank, communications are not encrypted. If you remove this field from your
	// configuration at the same time as deleting or recreating a referenced ServerTlsPolicy resource, you will receive a
	// resourceInUseByAnotherResource error. Use lifecycle.create_before_destroy within the ServerTlsPolicy resource to avoid
	// this.
	ServerTlsPolicy *string `pulumi:"serverTlsPolicy"`
	// URLs to SslCertificate resources that are used to authenticate connections between users and the load balancer. At least
	// one SSL certificate must be specified. Currently, you may specify up to 15 SSL certificates. sslCertificates do not
	// apply when the load balancing scheme is set to INTERNAL_SELF_MANAGED.
	SslCertificates []string `pulumi:"sslCertificates"`
	// A reference to the Region SslPolicy resource that will be associated with the TargetHttpsProxy resource. If not set, the
	// TargetHttpsProxy resource will not have any SSL policy configured.
	SslPolicy *string                                `pulumi:"sslPolicy"`
	Timeouts  *ComputeRegionTargetHttpsProxyTimeouts `pulumi:"timeouts"`
	// A reference to the RegionUrlMap resource that defines the mapping from URL to the RegionBackendService.
	UrlMap string `pulumi:"urlMap"`
}

// The set of arguments for constructing a ComputeRegionTargetHttpsProxy resource.
type ComputeRegionTargetHttpsProxyArgs struct {
	// URLs to certificate manager certificate resources that are used to authenticate connections between users and the load
	// balancer. sslCertificates and certificateManagerCertificates can't be defined together. Accepted format is
	// '//certificatemanager.googleapis.com/projects/{project}/locations/{location}/certificates/{resourceName}' or just the
	// self_link 'projects/{project}/locations/{location}/certificates/{resourceName}'
	CertificateManagerCertificates  pulumi.StringArrayInput
	ComputeRegionTargetHttpsProxyId pulumi.StringPtrInput
	// An optional description of this resource.
	Description pulumi.StringPtrInput
	// Specifies how long to keep a connection open, after completing a response, while there is no matching traffic (in
	// seconds). If an HTTP keepalive is not specified, a default value (600 seconds) will be used. For Regioanl HTTP(S) load
	// balancer, the minimum allowed value is 5 seconds and the maximum allowed value is 600 seconds.
	HttpKeepAliveTimeoutSec pulumi.Float64PtrInput
	// Name of the resource. Provided by the client when the resource is created. The name must be 1-63 characters long, and
	// comply with RFC1035. Specifically, the name must be 1-63 characters long and match the regular expression 'a-z?' which
	// means the first character must be a lowercase letter, and all following characters must be a dash, lowercase letter, or
	// digit, except the last character, which cannot be a dash.
	Name    pulumi.StringPtrInput
	Project pulumi.StringPtrInput
	// The Region in which the created target https proxy should reside. If it is not provided, the provider region is used.
	Region pulumi.StringPtrInput
	// A URL referring to a networksecurity.ServerTlsPolicy resource that describes how the proxy should authenticate inbound
	// traffic. serverTlsPolicy only applies to a global TargetHttpsProxy attached to globalForwardingRules with the
	// loadBalancingScheme set to INTERNAL_SELF_MANAGED or EXTERNAL or EXTERNAL_MANAGED. For details which ServerTlsPolicy
	// resources are accepted with INTERNAL_SELF_MANAGED and which with EXTERNAL, EXTERNAL_MANAGED loadBalancingScheme consult
	// ServerTlsPolicy documentation. If left blank, communications are not encrypted. If you remove this field from your
	// configuration at the same time as deleting or recreating a referenced ServerTlsPolicy resource, you will receive a
	// resourceInUseByAnotherResource error. Use lifecycle.create_before_destroy within the ServerTlsPolicy resource to avoid
	// this.
	ServerTlsPolicy pulumi.StringPtrInput
	// URLs to SslCertificate resources that are used to authenticate connections between users and the load balancer. At least
	// one SSL certificate must be specified. Currently, you may specify up to 15 SSL certificates. sslCertificates do not
	// apply when the load balancing scheme is set to INTERNAL_SELF_MANAGED.
	SslCertificates pulumi.StringArrayInput
	// A reference to the Region SslPolicy resource that will be associated with the TargetHttpsProxy resource. If not set, the
	// TargetHttpsProxy resource will not have any SSL policy configured.
	SslPolicy pulumi.StringPtrInput
	Timeouts  ComputeRegionTargetHttpsProxyTimeoutsPtrInput
	// A reference to the RegionUrlMap resource that defines the mapping from URL to the RegionBackendService.
	UrlMap pulumi.StringInput
}

func (ComputeRegionTargetHttpsProxyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*computeRegionTargetHttpsProxyArgs)(nil)).Elem()
}

type ComputeRegionTargetHttpsProxyInput interface {
	pulumi.Input

	ToComputeRegionTargetHttpsProxyOutput() ComputeRegionTargetHttpsProxyOutput
	ToComputeRegionTargetHttpsProxyOutputWithContext(ctx context.Context) ComputeRegionTargetHttpsProxyOutput
}

func (*ComputeRegionTargetHttpsProxy) ElementType() reflect.Type {
	return reflect.TypeOf((**ComputeRegionTargetHttpsProxy)(nil)).Elem()
}

func (i *ComputeRegionTargetHttpsProxy) ToComputeRegionTargetHttpsProxyOutput() ComputeRegionTargetHttpsProxyOutput {
	return i.ToComputeRegionTargetHttpsProxyOutputWithContext(context.Background())
}

func (i *ComputeRegionTargetHttpsProxy) ToComputeRegionTargetHttpsProxyOutputWithContext(ctx context.Context) ComputeRegionTargetHttpsProxyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ComputeRegionTargetHttpsProxyOutput)
}

type ComputeRegionTargetHttpsProxyOutput struct{ *pulumi.OutputState }

func (ComputeRegionTargetHttpsProxyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ComputeRegionTargetHttpsProxy)(nil)).Elem()
}

func (o ComputeRegionTargetHttpsProxyOutput) ToComputeRegionTargetHttpsProxyOutput() ComputeRegionTargetHttpsProxyOutput {
	return o
}

func (o ComputeRegionTargetHttpsProxyOutput) ToComputeRegionTargetHttpsProxyOutputWithContext(ctx context.Context) ComputeRegionTargetHttpsProxyOutput {
	return o
}

// URLs to certificate manager certificate resources that are used to authenticate connections between users and the load
// balancer. sslCertificates and certificateManagerCertificates can't be defined together. Accepted format is
// '//certificatemanager.googleapis.com/projects/{project}/locations/{location}/certificates/{resourceName}' or just the
// self_link 'projects/{project}/locations/{location}/certificates/{resourceName}'
func (o ComputeRegionTargetHttpsProxyOutput) CertificateManagerCertificates() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ComputeRegionTargetHttpsProxy) pulumi.StringArrayOutput {
		return v.CertificateManagerCertificates
	}).(pulumi.StringArrayOutput)
}

func (o ComputeRegionTargetHttpsProxyOutput) ComputeRegionTargetHttpsProxyId() pulumi.StringOutput {
	return o.ApplyT(func(v *ComputeRegionTargetHttpsProxy) pulumi.StringOutput { return v.ComputeRegionTargetHttpsProxyId }).(pulumi.StringOutput)
}

// Creation timestamp in RFC3339 text format.
func (o ComputeRegionTargetHttpsProxyOutput) CreationTimestamp() pulumi.StringOutput {
	return o.ApplyT(func(v *ComputeRegionTargetHttpsProxy) pulumi.StringOutput { return v.CreationTimestamp }).(pulumi.StringOutput)
}

// An optional description of this resource.
func (o ComputeRegionTargetHttpsProxyOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ComputeRegionTargetHttpsProxy) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Specifies how long to keep a connection open, after completing a response, while there is no matching traffic (in
// seconds). If an HTTP keepalive is not specified, a default value (600 seconds) will be used. For Regioanl HTTP(S) load
// balancer, the minimum allowed value is 5 seconds and the maximum allowed value is 600 seconds.
func (o ComputeRegionTargetHttpsProxyOutput) HttpKeepAliveTimeoutSec() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *ComputeRegionTargetHttpsProxy) pulumi.Float64PtrOutput { return v.HttpKeepAliveTimeoutSec }).(pulumi.Float64PtrOutput)
}

// Name of the resource. Provided by the client when the resource is created. The name must be 1-63 characters long, and
// comply with RFC1035. Specifically, the name must be 1-63 characters long and match the regular expression 'a-z?' which
// means the first character must be a lowercase letter, and all following characters must be a dash, lowercase letter, or
// digit, except the last character, which cannot be a dash.
func (o ComputeRegionTargetHttpsProxyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ComputeRegionTargetHttpsProxy) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o ComputeRegionTargetHttpsProxyOutput) Project() pulumi.StringOutput {
	return o.ApplyT(func(v *ComputeRegionTargetHttpsProxy) pulumi.StringOutput { return v.Project }).(pulumi.StringOutput)
}

// The unique identifier for the resource.
func (o ComputeRegionTargetHttpsProxyOutput) ProxyId() pulumi.Float64Output {
	return o.ApplyT(func(v *ComputeRegionTargetHttpsProxy) pulumi.Float64Output { return v.ProxyId }).(pulumi.Float64Output)
}

// The Region in which the created target https proxy should reside. If it is not provided, the provider region is used.
func (o ComputeRegionTargetHttpsProxyOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *ComputeRegionTargetHttpsProxy) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

func (o ComputeRegionTargetHttpsProxyOutput) SelfLink() pulumi.StringOutput {
	return o.ApplyT(func(v *ComputeRegionTargetHttpsProxy) pulumi.StringOutput { return v.SelfLink }).(pulumi.StringOutput)
}

// A URL referring to a networksecurity.ServerTlsPolicy resource that describes how the proxy should authenticate inbound
// traffic. serverTlsPolicy only applies to a global TargetHttpsProxy attached to globalForwardingRules with the
// loadBalancingScheme set to INTERNAL_SELF_MANAGED or EXTERNAL or EXTERNAL_MANAGED. For details which ServerTlsPolicy
// resources are accepted with INTERNAL_SELF_MANAGED and which with EXTERNAL, EXTERNAL_MANAGED loadBalancingScheme consult
// ServerTlsPolicy documentation. If left blank, communications are not encrypted. If you remove this field from your
// configuration at the same time as deleting or recreating a referenced ServerTlsPolicy resource, you will receive a
// resourceInUseByAnotherResource error. Use lifecycle.create_before_destroy within the ServerTlsPolicy resource to avoid
// this.
func (o ComputeRegionTargetHttpsProxyOutput) ServerTlsPolicy() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ComputeRegionTargetHttpsProxy) pulumi.StringPtrOutput { return v.ServerTlsPolicy }).(pulumi.StringPtrOutput)
}

// URLs to SslCertificate resources that are used to authenticate connections between users and the load balancer. At least
// one SSL certificate must be specified. Currently, you may specify up to 15 SSL certificates. sslCertificates do not
// apply when the load balancing scheme is set to INTERNAL_SELF_MANAGED.
func (o ComputeRegionTargetHttpsProxyOutput) SslCertificates() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ComputeRegionTargetHttpsProxy) pulumi.StringArrayOutput { return v.SslCertificates }).(pulumi.StringArrayOutput)
}

// A reference to the Region SslPolicy resource that will be associated with the TargetHttpsProxy resource. If not set, the
// TargetHttpsProxy resource will not have any SSL policy configured.
func (o ComputeRegionTargetHttpsProxyOutput) SslPolicy() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ComputeRegionTargetHttpsProxy) pulumi.StringPtrOutput { return v.SslPolicy }).(pulumi.StringPtrOutput)
}

func (o ComputeRegionTargetHttpsProxyOutput) Timeouts() ComputeRegionTargetHttpsProxyTimeoutsPtrOutput {
	return o.ApplyT(func(v *ComputeRegionTargetHttpsProxy) ComputeRegionTargetHttpsProxyTimeoutsPtrOutput {
		return v.Timeouts
	}).(ComputeRegionTargetHttpsProxyTimeoutsPtrOutput)
}

// A reference to the RegionUrlMap resource that defines the mapping from URL to the RegionBackendService.
func (o ComputeRegionTargetHttpsProxyOutput) UrlMap() pulumi.StringOutput {
	return o.ApplyT(func(v *ComputeRegionTargetHttpsProxy) pulumi.StringOutput { return v.UrlMap }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ComputeRegionTargetHttpsProxyInput)(nil)).Elem(), &ComputeRegionTargetHttpsProxy{})
	pulumi.RegisterOutputType(ComputeRegionTargetHttpsProxyOutput{})
}
