// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package google

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/google/v6/google/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupArtifactRegistryRepositoryIamPolicy(ctx *pulumi.Context, args *LookupArtifactRegistryRepositoryIamPolicyArgs, opts ...pulumi.InvokeOption) (*LookupArtifactRegistryRepositoryIamPolicyResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupArtifactRegistryRepositoryIamPolicyResult
	err = ctx.InvokePackage("google:index/getArtifactRegistryRepositoryIamPolicy:getArtifactRegistryRepositoryIamPolicy", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getArtifactRegistryRepositoryIamPolicy.
type LookupArtifactRegistryRepositoryIamPolicyArgs struct {
	Id         *string `pulumi:"id"`
	Location   *string `pulumi:"location"`
	Project    *string `pulumi:"project"`
	Repository string  `pulumi:"repository"`
}

// A collection of values returned by getArtifactRegistryRepositoryIamPolicy.
type LookupArtifactRegistryRepositoryIamPolicyResult struct {
	Etag       string `pulumi:"etag"`
	Id         string `pulumi:"id"`
	Location   string `pulumi:"location"`
	PolicyData string `pulumi:"policyData"`
	Project    string `pulumi:"project"`
	Repository string `pulumi:"repository"`
}

func LookupArtifactRegistryRepositoryIamPolicyOutput(ctx *pulumi.Context, args LookupArtifactRegistryRepositoryIamPolicyOutputArgs, opts ...pulumi.InvokeOption) LookupArtifactRegistryRepositoryIamPolicyResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupArtifactRegistryRepositoryIamPolicyResultOutput, error) {
			args := v.(LookupArtifactRegistryRepositoryIamPolicyArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupArtifactRegistryRepositoryIamPolicyResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("google:index/getArtifactRegistryRepositoryIamPolicy:getArtifactRegistryRepositoryIamPolicy", args, LookupArtifactRegistryRepositoryIamPolicyResultOutput{}, options).(LookupArtifactRegistryRepositoryIamPolicyResultOutput), nil
		}).(LookupArtifactRegistryRepositoryIamPolicyResultOutput)
}

// A collection of arguments for invoking getArtifactRegistryRepositoryIamPolicy.
type LookupArtifactRegistryRepositoryIamPolicyOutputArgs struct {
	Id         pulumi.StringPtrInput `pulumi:"id"`
	Location   pulumi.StringPtrInput `pulumi:"location"`
	Project    pulumi.StringPtrInput `pulumi:"project"`
	Repository pulumi.StringInput    `pulumi:"repository"`
}

func (LookupArtifactRegistryRepositoryIamPolicyOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupArtifactRegistryRepositoryIamPolicyArgs)(nil)).Elem()
}

// A collection of values returned by getArtifactRegistryRepositoryIamPolicy.
type LookupArtifactRegistryRepositoryIamPolicyResultOutput struct{ *pulumi.OutputState }

func (LookupArtifactRegistryRepositoryIamPolicyResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupArtifactRegistryRepositoryIamPolicyResult)(nil)).Elem()
}

func (o LookupArtifactRegistryRepositoryIamPolicyResultOutput) ToLookupArtifactRegistryRepositoryIamPolicyResultOutput() LookupArtifactRegistryRepositoryIamPolicyResultOutput {
	return o
}

func (o LookupArtifactRegistryRepositoryIamPolicyResultOutput) ToLookupArtifactRegistryRepositoryIamPolicyResultOutputWithContext(ctx context.Context) LookupArtifactRegistryRepositoryIamPolicyResultOutput {
	return o
}

func (o LookupArtifactRegistryRepositoryIamPolicyResultOutput) Etag() pulumi.StringOutput {
	return o.ApplyT(func(v LookupArtifactRegistryRepositoryIamPolicyResult) string { return v.Etag }).(pulumi.StringOutput)
}

func (o LookupArtifactRegistryRepositoryIamPolicyResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupArtifactRegistryRepositoryIamPolicyResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupArtifactRegistryRepositoryIamPolicyResultOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v LookupArtifactRegistryRepositoryIamPolicyResult) string { return v.Location }).(pulumi.StringOutput)
}

func (o LookupArtifactRegistryRepositoryIamPolicyResultOutput) PolicyData() pulumi.StringOutput {
	return o.ApplyT(func(v LookupArtifactRegistryRepositoryIamPolicyResult) string { return v.PolicyData }).(pulumi.StringOutput)
}

func (o LookupArtifactRegistryRepositoryIamPolicyResultOutput) Project() pulumi.StringOutput {
	return o.ApplyT(func(v LookupArtifactRegistryRepositoryIamPolicyResult) string { return v.Project }).(pulumi.StringOutput)
}

func (o LookupArtifactRegistryRepositoryIamPolicyResultOutput) Repository() pulumi.StringOutput {
	return o.ApplyT(func(v LookupArtifactRegistryRepositoryIamPolicyResult) string { return v.Repository }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupArtifactRegistryRepositoryIamPolicyResultOutput{})
}
