// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package google

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/google/v6/google/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupBackupDrBackupVault(ctx *pulumi.Context, args *LookupBackupDrBackupVaultArgs, opts ...pulumi.InvokeOption) (*LookupBackupDrBackupVaultResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupBackupDrBackupVaultResult
	err = ctx.InvokePackage("google:index/getBackupDrBackupVault:getBackupDrBackupVault", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getBackupDrBackupVault.
type LookupBackupDrBackupVaultArgs struct {
	BackupVaultId string  `pulumi:"backupVaultId"`
	Id            *string `pulumi:"id"`
	Location      string  `pulumi:"location"`
	Project       *string `pulumi:"project"`
}

// A collection of values returned by getBackupDrBackupVault.
type LookupBackupDrBackupVaultResult struct {
	AccessRestriction                      string            `pulumi:"accessRestriction"`
	AllowMissing                           bool              `pulumi:"allowMissing"`
	Annotations                            map[string]string `pulumi:"annotations"`
	BackupCount                            string            `pulumi:"backupCount"`
	BackupMinimumEnforcedRetentionDuration string            `pulumi:"backupMinimumEnforcedRetentionDuration"`
	BackupVaultId                          string            `pulumi:"backupVaultId"`
	CreateTime                             string            `pulumi:"createTime"`
	Deletable                              bool              `pulumi:"deletable"`
	Description                            string            `pulumi:"description"`
	EffectiveAnnotations                   map[string]string `pulumi:"effectiveAnnotations"`
	EffectiveLabels                        map[string]string `pulumi:"effectiveLabels"`
	EffectiveTime                          string            `pulumi:"effectiveTime"`
	Etag                                   string            `pulumi:"etag"`
	ForceDelete                            bool              `pulumi:"forceDelete"`
	ForceUpdate                            bool              `pulumi:"forceUpdate"`
	Id                                     string            `pulumi:"id"`
	IgnoreBackupPlanReferences             bool              `pulumi:"ignoreBackupPlanReferences"`
	IgnoreInactiveDatasources              bool              `pulumi:"ignoreInactiveDatasources"`
	Labels                                 map[string]string `pulumi:"labels"`
	Location                               string            `pulumi:"location"`
	Name                                   string            `pulumi:"name"`
	Project                                *string           `pulumi:"project"`
	ServiceAccount                         string            `pulumi:"serviceAccount"`
	State                                  string            `pulumi:"state"`
	TerraformLabels                        map[string]string `pulumi:"terraformLabels"`
	TotalStoredBytes                       string            `pulumi:"totalStoredBytes"`
	Uid                                    string            `pulumi:"uid"`
	UpdateTime                             string            `pulumi:"updateTime"`
}

func LookupBackupDrBackupVaultOutput(ctx *pulumi.Context, args LookupBackupDrBackupVaultOutputArgs, opts ...pulumi.InvokeOption) LookupBackupDrBackupVaultResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupBackupDrBackupVaultResultOutput, error) {
			args := v.(LookupBackupDrBackupVaultArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupBackupDrBackupVaultResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("google:index/getBackupDrBackupVault:getBackupDrBackupVault", args, LookupBackupDrBackupVaultResultOutput{}, options).(LookupBackupDrBackupVaultResultOutput), nil
		}).(LookupBackupDrBackupVaultResultOutput)
}

// A collection of arguments for invoking getBackupDrBackupVault.
type LookupBackupDrBackupVaultOutputArgs struct {
	BackupVaultId pulumi.StringInput    `pulumi:"backupVaultId"`
	Id            pulumi.StringPtrInput `pulumi:"id"`
	Location      pulumi.StringInput    `pulumi:"location"`
	Project       pulumi.StringPtrInput `pulumi:"project"`
}

func (LookupBackupDrBackupVaultOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupBackupDrBackupVaultArgs)(nil)).Elem()
}

// A collection of values returned by getBackupDrBackupVault.
type LookupBackupDrBackupVaultResultOutput struct{ *pulumi.OutputState }

func (LookupBackupDrBackupVaultResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupBackupDrBackupVaultResult)(nil)).Elem()
}

func (o LookupBackupDrBackupVaultResultOutput) ToLookupBackupDrBackupVaultResultOutput() LookupBackupDrBackupVaultResultOutput {
	return o
}

func (o LookupBackupDrBackupVaultResultOutput) ToLookupBackupDrBackupVaultResultOutputWithContext(ctx context.Context) LookupBackupDrBackupVaultResultOutput {
	return o
}

func (o LookupBackupDrBackupVaultResultOutput) AccessRestriction() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) string { return v.AccessRestriction }).(pulumi.StringOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) AllowMissing() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) bool { return v.AllowMissing }).(pulumi.BoolOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) Annotations() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) map[string]string { return v.Annotations }).(pulumi.StringMapOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) BackupCount() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) string { return v.BackupCount }).(pulumi.StringOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) BackupMinimumEnforcedRetentionDuration() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) string { return v.BackupMinimumEnforcedRetentionDuration }).(pulumi.StringOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) BackupVaultId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) string { return v.BackupVaultId }).(pulumi.StringOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) CreateTime() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) string { return v.CreateTime }).(pulumi.StringOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) Deletable() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) bool { return v.Deletable }).(pulumi.BoolOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) EffectiveAnnotations() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) map[string]string { return v.EffectiveAnnotations }).(pulumi.StringMapOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) EffectiveLabels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) map[string]string { return v.EffectiveLabels }).(pulumi.StringMapOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) EffectiveTime() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) string { return v.EffectiveTime }).(pulumi.StringOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) Etag() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) string { return v.Etag }).(pulumi.StringOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) ForceDelete() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) bool { return v.ForceDelete }).(pulumi.BoolOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) ForceUpdate() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) bool { return v.ForceUpdate }).(pulumi.BoolOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) IgnoreBackupPlanReferences() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) bool { return v.IgnoreBackupPlanReferences }).(pulumi.BoolOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) IgnoreInactiveDatasources() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) bool { return v.IgnoreInactiveDatasources }).(pulumi.BoolOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) string { return v.Location }).(pulumi.StringOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) *string { return v.Project }).(pulumi.StringPtrOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) ServiceAccount() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) string { return v.ServiceAccount }).(pulumi.StringOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) string { return v.State }).(pulumi.StringOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) TerraformLabels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) map[string]string { return v.TerraformLabels }).(pulumi.StringMapOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) TotalStoredBytes() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) string { return v.TotalStoredBytes }).(pulumi.StringOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) Uid() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) string { return v.Uid }).(pulumi.StringOutput)
}

func (o LookupBackupDrBackupVaultResultOutput) UpdateTime() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBackupDrBackupVaultResult) string { return v.UpdateTime }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupBackupDrBackupVaultResultOutput{})
}
