// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package google

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/google/v6/google/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetComputeNetworks(ctx *pulumi.Context, args *GetComputeNetworksArgs, opts ...pulumi.InvokeOption) (*GetComputeNetworksResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetComputeNetworksResult
	err = ctx.InvokePackage("google:index/getComputeNetworks:getComputeNetworks", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getComputeNetworks.
type GetComputeNetworksArgs struct {
	Id      *string `pulumi:"id"`
	Project *string `pulumi:"project"`
}

// A collection of values returned by getComputeNetworks.
type GetComputeNetworksResult struct {
	Id       string   `pulumi:"id"`
	Networks []string `pulumi:"networks"`
	Project  *string  `pulumi:"project"`
	SelfLink string   `pulumi:"selfLink"`
}

func GetComputeNetworksOutput(ctx *pulumi.Context, args GetComputeNetworksOutputArgs, opts ...pulumi.InvokeOption) GetComputeNetworksResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetComputeNetworksResultOutput, error) {
			args := v.(GetComputeNetworksArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetComputeNetworksResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("google:index/getComputeNetworks:getComputeNetworks", args, GetComputeNetworksResultOutput{}, options).(GetComputeNetworksResultOutput), nil
		}).(GetComputeNetworksResultOutput)
}

// A collection of arguments for invoking getComputeNetworks.
type GetComputeNetworksOutputArgs struct {
	Id      pulumi.StringPtrInput `pulumi:"id"`
	Project pulumi.StringPtrInput `pulumi:"project"`
}

func (GetComputeNetworksOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetComputeNetworksArgs)(nil)).Elem()
}

// A collection of values returned by getComputeNetworks.
type GetComputeNetworksResultOutput struct{ *pulumi.OutputState }

func (GetComputeNetworksResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetComputeNetworksResult)(nil)).Elem()
}

func (o GetComputeNetworksResultOutput) ToGetComputeNetworksResultOutput() GetComputeNetworksResultOutput {
	return o
}

func (o GetComputeNetworksResultOutput) ToGetComputeNetworksResultOutputWithContext(ctx context.Context) GetComputeNetworksResultOutput {
	return o
}

func (o GetComputeNetworksResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetComputeNetworksResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetComputeNetworksResultOutput) Networks() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetComputeNetworksResult) []string { return v.Networks }).(pulumi.StringArrayOutput)
}

func (o GetComputeNetworksResultOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetComputeNetworksResult) *string { return v.Project }).(pulumi.StringPtrOutput)
}

func (o GetComputeNetworksResultOutput) SelfLink() pulumi.StringOutput {
	return o.ApplyT(func(v GetComputeNetworksResult) string { return v.SelfLink }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetComputeNetworksResultOutput{})
}
