// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package google

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/google/v6/google/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupEndpointsServiceConsumersIamPolicy(ctx *pulumi.Context, args *LookupEndpointsServiceConsumersIamPolicyArgs, opts ...pulumi.InvokeOption) (*LookupEndpointsServiceConsumersIamPolicyResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupEndpointsServiceConsumersIamPolicyResult
	err = ctx.InvokePackage("google:index/getEndpointsServiceConsumersIamPolicy:getEndpointsServiceConsumersIamPolicy", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getEndpointsServiceConsumersIamPolicy.
type LookupEndpointsServiceConsumersIamPolicyArgs struct {
	ConsumerProject string  `pulumi:"consumerProject"`
	Id              *string `pulumi:"id"`
	ServiceName     string  `pulumi:"serviceName"`
}

// A collection of values returned by getEndpointsServiceConsumersIamPolicy.
type LookupEndpointsServiceConsumersIamPolicyResult struct {
	ConsumerProject string `pulumi:"consumerProject"`
	Etag            string `pulumi:"etag"`
	Id              string `pulumi:"id"`
	PolicyData      string `pulumi:"policyData"`
	ServiceName     string `pulumi:"serviceName"`
}

func LookupEndpointsServiceConsumersIamPolicyOutput(ctx *pulumi.Context, args LookupEndpointsServiceConsumersIamPolicyOutputArgs, opts ...pulumi.InvokeOption) LookupEndpointsServiceConsumersIamPolicyResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupEndpointsServiceConsumersIamPolicyResultOutput, error) {
			args := v.(LookupEndpointsServiceConsumersIamPolicyArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupEndpointsServiceConsumersIamPolicyResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("google:index/getEndpointsServiceConsumersIamPolicy:getEndpointsServiceConsumersIamPolicy", args, LookupEndpointsServiceConsumersIamPolicyResultOutput{}, options).(LookupEndpointsServiceConsumersIamPolicyResultOutput), nil
		}).(LookupEndpointsServiceConsumersIamPolicyResultOutput)
}

// A collection of arguments for invoking getEndpointsServiceConsumersIamPolicy.
type LookupEndpointsServiceConsumersIamPolicyOutputArgs struct {
	ConsumerProject pulumi.StringInput    `pulumi:"consumerProject"`
	Id              pulumi.StringPtrInput `pulumi:"id"`
	ServiceName     pulumi.StringInput    `pulumi:"serviceName"`
}

func (LookupEndpointsServiceConsumersIamPolicyOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupEndpointsServiceConsumersIamPolicyArgs)(nil)).Elem()
}

// A collection of values returned by getEndpointsServiceConsumersIamPolicy.
type LookupEndpointsServiceConsumersIamPolicyResultOutput struct{ *pulumi.OutputState }

func (LookupEndpointsServiceConsumersIamPolicyResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupEndpointsServiceConsumersIamPolicyResult)(nil)).Elem()
}

func (o LookupEndpointsServiceConsumersIamPolicyResultOutput) ToLookupEndpointsServiceConsumersIamPolicyResultOutput() LookupEndpointsServiceConsumersIamPolicyResultOutput {
	return o
}

func (o LookupEndpointsServiceConsumersIamPolicyResultOutput) ToLookupEndpointsServiceConsumersIamPolicyResultOutputWithContext(ctx context.Context) LookupEndpointsServiceConsumersIamPolicyResultOutput {
	return o
}

func (o LookupEndpointsServiceConsumersIamPolicyResultOutput) ConsumerProject() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEndpointsServiceConsumersIamPolicyResult) string { return v.ConsumerProject }).(pulumi.StringOutput)
}

func (o LookupEndpointsServiceConsumersIamPolicyResultOutput) Etag() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEndpointsServiceConsumersIamPolicyResult) string { return v.Etag }).(pulumi.StringOutput)
}

func (o LookupEndpointsServiceConsumersIamPolicyResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEndpointsServiceConsumersIamPolicyResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupEndpointsServiceConsumersIamPolicyResultOutput) PolicyData() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEndpointsServiceConsumersIamPolicyResult) string { return v.PolicyData }).(pulumi.StringOutput)
}

func (o LookupEndpointsServiceConsumersIamPolicyResultOutput) ServiceName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEndpointsServiceConsumersIamPolicyResult) string { return v.ServiceName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupEndpointsServiceConsumersIamPolicyResultOutput{})
}
